// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: openshield/v1/attestation.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AttestationReport carries a device's TPM quote from the endpoint to the gateway
// so the gateway can verify it and decide whether the device is hardware-attested
// (ZT-1). It carries EVIDENCE, not a verdict: note the absence of any self-asserted
// `attested` boolean — the gateway computes attestation from the quote against the
// device's enrolled AK and golden PCR baseline. A field the endpoint could set to
// `attested=true` would defeat the whole point of attestation, so it does not exist.
type AttestationReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The device's pseudonymous subject (D23), matching its enrollment.
	Subject string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	// The server-issued nonce this quote answers (anti-replay; the gateway checks it
	// is a fresh nonce it issued and has not consumed).
	Nonce []byte `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// The marshaled TPMS_ATTEST quote structure.
	QuoteAttest []byte `protobuf:"bytes,3,opt,name=quote_attest,json=quoteAttest,proto3" json:"quote_attest,omitempty"`
	// The ECDSA signature over quote_attest, as (r, s).
	QuoteSigR     []byte `protobuf:"bytes,4,opt,name=quote_sig_r,json=quoteSigR,proto3" json:"quote_sig_r,omitempty"`
	QuoteSigS     []byte `protobuf:"bytes,5,opt,name=quote_sig_s,json=quoteSigS,proto3" json:"quote_sig_s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttestationReport) Reset() {
	*x = AttestationReport{}
	mi := &file_openshield_v1_attestation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestationReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationReport) ProtoMessage() {}

func (x *AttestationReport) ProtoReflect() protoreflect.Message {
	mi := &file_openshield_v1_attestation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationReport.ProtoReflect.Descriptor instead.
func (*AttestationReport) Descriptor() ([]byte, []int) {
	return file_openshield_v1_attestation_proto_rawDescGZIP(), []int{0}
}

func (x *AttestationReport) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *AttestationReport) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *AttestationReport) GetQuoteAttest() []byte {
	if x != nil {
		return x.QuoteAttest
	}
	return nil
}

func (x *AttestationReport) GetQuoteSigR() []byte {
	if x != nil {
		return x.QuoteSigR
	}
	return nil
}

func (x *AttestationReport) GetQuoteSigS() []byte {
	if x != nil {
		return x.QuoteSigS
	}
	return nil
}

var File_openshield_v1_attestation_proto protoreflect.FileDescriptor

const file_openshield_v1_attestation_proto_rawDesc = "" +
	"\n" +
	"\x1fopenshield/v1/attestation.proto\x12\ropenshield.v1\"\xa6\x01\n" +
	"\x11AttestationReport\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12!\n" +
	"\fquote_attest\x18\x03 \x01(\fR\vquoteAttest\x12\x1e\n" +
	"\vquote_sig_r\x18\x04 \x01(\fR\tquoteSigR\x12\x1e\n" +
	"\vquote_sig_s\x18\x05 \x01(\fR\tquoteSigSB@Z>github.com/lucianoengel/openshield/internal/core/corev1;corev1b\x06proto3"

var (
	file_openshield_v1_attestation_proto_rawDescOnce sync.Once
	file_openshield_v1_attestation_proto_rawDescData []byte
)

func file_openshield_v1_attestation_proto_rawDescGZIP() []byte {
	file_openshield_v1_attestation_proto_rawDescOnce.Do(func() {
		file_openshield_v1_attestation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openshield_v1_attestation_proto_rawDesc), len(file_openshield_v1_attestation_proto_rawDesc)))
	})
	return file_openshield_v1_attestation_proto_rawDescData
}

var file_openshield_v1_attestation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_openshield_v1_attestation_proto_goTypes = []any{
	(*AttestationReport)(nil), // 0: openshield.v1.AttestationReport
}
var file_openshield_v1_attestation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_openshield_v1_attestation_proto_init() }
func file_openshield_v1_attestation_proto_init() {
	if File_openshield_v1_attestation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openshield_v1_attestation_proto_rawDesc), len(file_openshield_v1_attestation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openshield_v1_attestation_proto_goTypes,
		DependencyIndexes: file_openshield_v1_attestation_proto_depIdxs,
		MessageInfos:      file_openshield_v1_attestation_proto_msgTypes,
	}.Build()
	File_openshield_v1_attestation_proto = out.File
	file_openshield_v1_attestation_proto_goTypes = nil
	file_openshield_v1_attestation_proto_depIdxs = nil
}
