// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: openshield/v1/classification.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DetectorType is a closed enum rather than a string. A free-form detector name
// can itself leak what it detected — a detector named for a customer, project or
// person — reintroducing the leak the summary type exists to prevent.
type DetectorType int32

const (
	DetectorType_DETECTOR_TYPE_UNSPECIFIED DetectorType = 0
	DetectorType_DETECTOR_TYPE_CPF         DetectorType = 1
	DetectorType_DETECTOR_TYPE_SSN         DetectorType = 2
	DetectorType_DETECTOR_TYPE_CREDIT_CARD DetectorType = 3
	DetectorType_DETECTOR_TYPE_EMAIL       DetectorType = 4
	DetectorType_DETECTOR_TYPE_PHONE       DetectorType = 5
	// Secrets / credentials (Phase D2). Structural detectors — a PEM block, a
	// prefixed cloud key, a decodable JWT — so a hit is strong, low-FP evidence.
	DetectorType_DETECTOR_TYPE_PRIVATE_KEY    DetectorType = 6
	DetectorType_DETECTOR_TYPE_AWS_ACCESS_KEY DetectorType = 7
	DetectorType_DETECTOR_TYPE_JWT            DetectorType = 8
	DetectorType_DETECTOR_TYPE_API_TOKEN      DetectorType = 9
	// International PII (Phase D2 remainder). IBAN has a mod-97 checksum (a strong
	// validator like CPF); health-data is keyword/dictionary evidence (weaker, no
	// checksum — its confidence is capped accordingly).
	DetectorType_DETECTOR_TYPE_IBAN        DetectorType = 10
	DetectorType_DETECTOR_TYPE_HEALTH_DATA DetectorType = 11
	// An operator-authored custom rule (Phase D3). All custom rules report this single
	// generic type — a free-form per-rule name could leak what it detects, so the closed
	// enum is preserved. Per-rule policy routing (a rule id in the contract) is a follow-up.
	DetectorType_DETECTOR_TYPE_CUSTOM DetectorType = 12
	// US bank routing number (ABA), DLP. A weighted mod-10 checksum (a strong validator like
	// Luhn) plus the Federal Reserve leading-digit range — evidence between a checksumless
	// structural rule and a full check-digit scheme.
	DetectorType_DETECTOR_TYPE_ABA_ROUTING DetectorType = 13
	// Canadian Social Insurance Number (SIN), DLP. A Luhn checksum over the conventional
	// grouped format — strong, low-FP evidence (the grouping distinguishes it from a bare
	// 9-digit run and the checksum filters the rest).
	DetectorType_DETECTOR_TYPE_CA_SIN DetectorType = 14
	// US National Provider Identifier (NPI), healthcare DLP. A 10-digit id that begins with 1
	// or 2 and carries a Luhn checksum over the 80840-prefixed number — a real check-digit
	// scheme, so a hit is strong evidence.
	DetectorType_DETECTOR_TYPE_NPI DetectorType = 15
	// UK NHS number, healthcare DLP. A 10-digit patient id in the conventional 3-3-4 spaced
	// grouping with a weighted mod-11 check digit — strong, low-FP evidence.
	DetectorType_DETECTOR_TYPE_UK_NHS DetectorType = 16
	// US Employer Identification Number (EIN), DLP. A 2-7 hyphenated tax id whose two-digit
	// prefix must be an IRS-assigned campus code — structural (no checksum), so a moderate
	// confidence like SSN.
	DetectorType_DETECTOR_TYPE_EIN DetectorType = 17
)

// Enum value maps for DetectorType.
var (
	DetectorType_name = map[int32]string{
		0:  "DETECTOR_TYPE_UNSPECIFIED",
		1:  "DETECTOR_TYPE_CPF",
		2:  "DETECTOR_TYPE_SSN",
		3:  "DETECTOR_TYPE_CREDIT_CARD",
		4:  "DETECTOR_TYPE_EMAIL",
		5:  "DETECTOR_TYPE_PHONE",
		6:  "DETECTOR_TYPE_PRIVATE_KEY",
		7:  "DETECTOR_TYPE_AWS_ACCESS_KEY",
		8:  "DETECTOR_TYPE_JWT",
		9:  "DETECTOR_TYPE_API_TOKEN",
		10: "DETECTOR_TYPE_IBAN",
		11: "DETECTOR_TYPE_HEALTH_DATA",
		12: "DETECTOR_TYPE_CUSTOM",
		13: "DETECTOR_TYPE_ABA_ROUTING",
		14: "DETECTOR_TYPE_CA_SIN",
		15: "DETECTOR_TYPE_NPI",
		16: "DETECTOR_TYPE_UK_NHS",
		17: "DETECTOR_TYPE_EIN",
	}
	DetectorType_value = map[string]int32{
		"DETECTOR_TYPE_UNSPECIFIED":    0,
		"DETECTOR_TYPE_CPF":            1,
		"DETECTOR_TYPE_SSN":            2,
		"DETECTOR_TYPE_CREDIT_CARD":    3,
		"DETECTOR_TYPE_EMAIL":          4,
		"DETECTOR_TYPE_PHONE":          5,
		"DETECTOR_TYPE_PRIVATE_KEY":    6,
		"DETECTOR_TYPE_AWS_ACCESS_KEY": 7,
		"DETECTOR_TYPE_JWT":            8,
		"DETECTOR_TYPE_API_TOKEN":      9,
		"DETECTOR_TYPE_IBAN":           10,
		"DETECTOR_TYPE_HEALTH_DATA":    11,
		"DETECTOR_TYPE_CUSTOM":         12,
		"DETECTOR_TYPE_ABA_ROUTING":    13,
		"DETECTOR_TYPE_CA_SIN":         14,
		"DETECTOR_TYPE_NPI":            15,
		"DETECTOR_TYPE_UK_NHS":         16,
		"DETECTOR_TYPE_EIN":            17,
	}
)

func (x DetectorType) Enum() *DetectorType {
	p := new(DetectorType)
	*p = x
	return p
}

func (x DetectorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DetectorType) Descriptor() protoreflect.EnumDescriptor {
	return file_openshield_v1_classification_proto_enumTypes[0].Descriptor()
}

func (DetectorType) Type() protoreflect.EnumType {
	return &file_openshield_v1_classification_proto_enumTypes[0]
}

func (x DetectorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DetectorType.Descriptor instead.
func (DetectorType) EnumDescriptor() ([]byte, []int) {
	return file_openshield_v1_classification_proto_rawDescGZIP(), []int{0}
}

// LocalMatch holds matched content. Host-only.
type LocalMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DetectorType  DetectorType           `protobuf:"varint,1,opt,name=detector_type,json=detectorType,proto3,enum=openshield.v1.DetectorType" json:"detector_type,omitempty"`
	Confidence    float64                `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	MatchedText   string                 `protobuf:"bytes,3,opt,name=matched_text,json=matchedText,proto3" json:"matched_text,omitempty"`
	Offset        uint32                 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalMatch) Reset() {
	*x = LocalMatch{}
	mi := &file_openshield_v1_classification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalMatch) ProtoMessage() {}

func (x *LocalMatch) ProtoReflect() protoreflect.Message {
	mi := &file_openshield_v1_classification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalMatch.ProtoReflect.Descriptor instead.
func (*LocalMatch) Descriptor() ([]byte, []int) {
	return file_openshield_v1_classification_proto_rawDescGZIP(), []int{0}
}

func (x *LocalMatch) GetDetectorType() DetectorType {
	if x != nil {
		return x.DetectorType
	}
	return DetectorType_DETECTOR_TYPE_UNSPECIFIED
}

func (x *LocalMatch) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *LocalMatch) GetMatchedText() string {
	if x != nil {
		return x.MatchedText
	}
	return ""
}

func (x *LocalMatch) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// LocalClassification NEVER leaves the host. It exists as a separate type from
// ClassificationSummary rather than as a redaction step, because redaction is a
// runtime behaviour that gets skipped — a debug logger, a retry, a new code
// path. Two types make the mistake a compile error (D10).
type LocalClassification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Matches       []*LocalMatch          `protobuf:"bytes,2,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalClassification) Reset() {
	*x = LocalClassification{}
	mi := &file_openshield_v1_classification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalClassification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalClassification) ProtoMessage() {}

func (x *LocalClassification) ProtoReflect() protoreflect.Message {
	mi := &file_openshield_v1_classification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalClassification.ProtoReflect.Descriptor instead.
func (*LocalClassification) Descriptor() ([]byte, []int) {
	return file_openshield_v1_classification_proto_rawDescGZIP(), []int{1}
}

func (x *LocalClassification) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *LocalClassification) GetMatches() []*LocalMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

// ClassificationSummary is the ONLY classification form permitted to cross the
// host boundary. Its field set is exactly these four and is asserted by test —
// no content, no hash, no fingerprint, no embedding (D10, D11).
type ClassificationSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	DetectorType  DetectorType           `protobuf:"varint,2,opt,name=detector_type,json=detectorType,proto3,enum=openshield.v1.DetectorType" json:"detector_type,omitempty"`
	Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	MatchCount    uint32                 `protobuf:"varint,4,opt,name=match_count,json=matchCount,proto3" json:"match_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassificationSummary) Reset() {
	*x = ClassificationSummary{}
	mi := &file_openshield_v1_classification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassificationSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassificationSummary) ProtoMessage() {}

func (x *ClassificationSummary) ProtoReflect() protoreflect.Message {
	mi := &file_openshield_v1_classification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassificationSummary.ProtoReflect.Descriptor instead.
func (*ClassificationSummary) Descriptor() ([]byte, []int) {
	return file_openshield_v1_classification_proto_rawDescGZIP(), []int{2}
}

func (x *ClassificationSummary) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ClassificationSummary) GetDetectorType() DetectorType {
	if x != nil {
		return x.DetectorType
	}
	return DetectorType_DETECTOR_TYPE_UNSPECIFIED
}

func (x *ClassificationSummary) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ClassificationSummary) GetMatchCount() uint32 {
	if x != nil {
		return x.MatchCount
	}
	return 0
}

var File_openshield_v1_classification_proto protoreflect.FileDescriptor

const file_openshield_v1_classification_proto_rawDesc = "" +
	"\n" +
	"\"openshield/v1/classification.proto\x12\ropenshield.v1\"\xa9\x01\n" +
	"\n" +
	"LocalMatch\x12@\n" +
	"\rdetector_type\x18\x01 \x01(\x0e2\x1b.openshield.v1.DetectorTypeR\fdetectorType\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01R\n" +
	"confidence\x12!\n" +
	"\fmatched_text\x18\x03 \x01(\tR\vmatchedText\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\rR\x06offset\"e\n" +
	"\x13LocalClassification\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x123\n" +
	"\amatches\x18\x02 \x03(\v2\x19.openshield.v1.LocalMatchR\amatches\"\xb5\x01\n" +
	"\x15ClassificationSummary\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12@\n" +
	"\rdetector_type\x18\x02 \x01(\x0e2\x1b.openshield.v1.DetectorTypeR\fdetectorType\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12\x1f\n" +
	"\vmatch_count\x18\x04 \x01(\rR\n" +
	"matchCount*\xf3\x03\n" +
	"\fDetectorType\x12\x1d\n" +
	"\x19DETECTOR_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11DETECTOR_TYPE_CPF\x10\x01\x12\x15\n" +
	"\x11DETECTOR_TYPE_SSN\x10\x02\x12\x1d\n" +
	"\x19DETECTOR_TYPE_CREDIT_CARD\x10\x03\x12\x17\n" +
	"\x13DETECTOR_TYPE_EMAIL\x10\x04\x12\x17\n" +
	"\x13DETECTOR_TYPE_PHONE\x10\x05\x12\x1d\n" +
	"\x19DETECTOR_TYPE_PRIVATE_KEY\x10\x06\x12 \n" +
	"\x1cDETECTOR_TYPE_AWS_ACCESS_KEY\x10\a\x12\x15\n" +
	"\x11DETECTOR_TYPE_JWT\x10\b\x12\x1b\n" +
	"\x17DETECTOR_TYPE_API_TOKEN\x10\t\x12\x16\n" +
	"\x12DETECTOR_TYPE_IBAN\x10\n" +
	"\x12\x1d\n" +
	"\x19DETECTOR_TYPE_HEALTH_DATA\x10\v\x12\x18\n" +
	"\x14DETECTOR_TYPE_CUSTOM\x10\f\x12\x1d\n" +
	"\x19DETECTOR_TYPE_ABA_ROUTING\x10\r\x12\x18\n" +
	"\x14DETECTOR_TYPE_CA_SIN\x10\x0e\x12\x15\n" +
	"\x11DETECTOR_TYPE_NPI\x10\x0f\x12\x18\n" +
	"\x14DETECTOR_TYPE_UK_NHS\x10\x10\x12\x15\n" +
	"\x11DETECTOR_TYPE_EIN\x10\x11B@Z>github.com/lucianoengel/openshield/internal/core/corev1;corev1b\x06proto3"

var (
	file_openshield_v1_classification_proto_rawDescOnce sync.Once
	file_openshield_v1_classification_proto_rawDescData []byte
)

func file_openshield_v1_classification_proto_rawDescGZIP() []byte {
	file_openshield_v1_classification_proto_rawDescOnce.Do(func() {
		file_openshield_v1_classification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openshield_v1_classification_proto_rawDesc), len(file_openshield_v1_classification_proto_rawDesc)))
	})
	return file_openshield_v1_classification_proto_rawDescData
}

var file_openshield_v1_classification_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_openshield_v1_classification_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_openshield_v1_classification_proto_goTypes = []any{
	(DetectorType)(0),             // 0: openshield.v1.DetectorType
	(*LocalMatch)(nil),            // 1: openshield.v1.LocalMatch
	(*LocalClassification)(nil),   // 2: openshield.v1.LocalClassification
	(*ClassificationSummary)(nil), // 3: openshield.v1.ClassificationSummary
}
var file_openshield_v1_classification_proto_depIdxs = []int32{
	0, // 0: openshield.v1.LocalMatch.detector_type:type_name -> openshield.v1.DetectorType
	1, // 1: openshield.v1.LocalClassification.matches:type_name -> openshield.v1.LocalMatch
	0, // 2: openshield.v1.ClassificationSummary.detector_type:type_name -> openshield.v1.DetectorType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_openshield_v1_classification_proto_init() }
func file_openshield_v1_classification_proto_init() {
	if File_openshield_v1_classification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openshield_v1_classification_proto_rawDesc), len(file_openshield_v1_classification_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openshield_v1_classification_proto_goTypes,
		DependencyIndexes: file_openshield_v1_classification_proto_depIdxs,
		EnumInfos:         file_openshield_v1_classification_proto_enumTypes,
		MessageInfos:      file_openshield_v1_classification_proto_msgTypes,
	}.Build()
	File_openshield_v1_classification_proto = out.File
	file_openshield_v1_classification_proto_goTypes = nil
	file_openshield_v1_classification_proto_depIdxs = nil
}
