// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: openshield/v1/decision.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Action is CLOSED and TYPED. Not a string, not a struct carrying parameters.
//
// The threat is specific: a compromised control plane distributing a policy
// whose action is "upload this file to a URL" — at the enforcement point,
// indistinguishable from the platform's own telemetry. A closed enum makes that
// unexpressible rather than merely forbidden (D14). This is what makes "the
// server coordinates, it does not control" architectural rather than
// aspirational.
//
// Adding a member here must also edit schema_test.go. That speed bump is
// deliberate: this is the most security-sensitive field in the system.
type Action int32

const (
	Action_ACTION_UNSPECIFIED      Action = 0
	Action_ACTION_ALLOW            Action = 1
	Action_ACTION_ALERT            Action = 2
	Action_ACTION_BLOCK            Action = 3
	Action_ACTION_QUARANTINE_LOCAL Action = 4
	Action_ACTION_ENCRYPT_LOCAL    Action = 5
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_ALLOW",
		2: "ACTION_ALERT",
		3: "ACTION_BLOCK",
		4: "ACTION_QUARANTINE_LOCAL",
		5: "ACTION_ENCRYPT_LOCAL",
	}
	Action_value = map[string]int32{
		"ACTION_UNSPECIFIED":      0,
		"ACTION_ALLOW":            1,
		"ACTION_ALERT":            2,
		"ACTION_BLOCK":            3,
		"ACTION_QUARANTINE_LOCAL": 4,
		"ACTION_ENCRYPT_LOCAL":    5,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_openshield_v1_decision_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_openshield_v1_decision_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_openshield_v1_decision_proto_rawDescGZIP(), []int{0}
}

// Decision is what the policy engine emits and the ONLY thing an enforcer sees.
//
// It is explainable to an investigator (reason, policy identity) and opaque
// about detection (no classifier ID, no pattern, no model, no matched content).
// Both properties matter: investigators need to know why, enforcers must not.
type Decision struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	DecisionId string                 `protobuf:"bytes,1,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	EventId    string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Action     Action                 `protobuf:"varint,3,opt,name=action,proto3,enum=openshield.v1.Action" json:"action,omitempty"`
	// Confidence, not certainty. Classification is noisy by nature; a contract
	// that modelled decisions as certain would push that noise silently into
	// enforcement (D4). Range [0.0, 1.0], mandatory — there is no implicit 1.0.
	Confidence    float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	PolicyId      string                 `protobuf:"bytes,6,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	PolicyVersion string                 `protobuf:"bytes,7,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	DecidedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=decided_at,json=decidedAt,proto3" json:"decided_at,omitempty"`
	// Version of the enrichment Context this decision was evaluated against.
	//
	// Added before any consumer existed, on the strength of the T-004 paper
	// design (docs/design-t004-peer-ueba.md): peer-baseline UEBA needs its risk
	// score to reach Policy, and without recording WHICH context version applied,
	// replay cannot reproduce a Decision — re-running against today's context
	// would legitimately produce a different answer.
	//
	// Empty in Phase 1: no Context exists yet. The field is here because
	// retrofitting one into a hash-chained audit ledger (T-009) would mean a
	// migration and a break in the chain's continuity.
	ContextVersion string `protobuf:"bytes,9,opt,name=context_version,json=contextVersion,proto3" json:"context_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Decision) Reset() {
	*x = Decision{}
	mi := &file_openshield_v1_decision_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_openshield_v1_decision_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_openshield_v1_decision_proto_rawDescGZIP(), []int{0}
}

func (x *Decision) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *Decision) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Decision) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_UNSPECIFIED
}

func (x *Decision) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Decision) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Decision) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *Decision) GetPolicyVersion() string {
	if x != nil {
		return x.PolicyVersion
	}
	return ""
}

func (x *Decision) GetDecidedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DecidedAt
	}
	return nil
}

func (x *Decision) GetContextVersion() string {
	if x != nil {
		return x.ContextVersion
	}
	return ""
}

var File_openshield_v1_decision_proto protoreflect.FileDescriptor

const file_openshield_v1_decision_proto_rawDesc = "" +
	"\n" +
	"\x1copenshield/v1/decision.proto\x12\ropenshield.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd5\x02\n" +
	"\bDecision\x12\x1f\n" +
	"\vdecision_id\x18\x01 \x01(\tR\n" +
	"decisionId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12-\n" +
	"\x06action\x18\x03 \x01(\x0e2\x15.openshield.v1.ActionR\x06action\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x1b\n" +
	"\tpolicy_id\x18\x06 \x01(\tR\bpolicyId\x12%\n" +
	"\x0epolicy_version\x18\a \x01(\tR\rpolicyVersion\x129\n" +
	"\n" +
	"decided_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tdecidedAt\x12'\n" +
	"\x0fcontext_version\x18\t \x01(\tR\x0econtextVersion*\x8d\x01\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fACTION_ALLOW\x10\x01\x12\x10\n" +
	"\fACTION_ALERT\x10\x02\x12\x10\n" +
	"\fACTION_BLOCK\x10\x03\x12\x1b\n" +
	"\x17ACTION_QUARANTINE_LOCAL\x10\x04\x12\x18\n" +
	"\x14ACTION_ENCRYPT_LOCAL\x10\x05B@Z>github.com/lucianoengel/openshield/internal/core/corev1;corev1b\x06proto3"

var (
	file_openshield_v1_decision_proto_rawDescOnce sync.Once
	file_openshield_v1_decision_proto_rawDescData []byte
)

func file_openshield_v1_decision_proto_rawDescGZIP() []byte {
	file_openshield_v1_decision_proto_rawDescOnce.Do(func() {
		file_openshield_v1_decision_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openshield_v1_decision_proto_rawDesc), len(file_openshield_v1_decision_proto_rawDesc)))
	})
	return file_openshield_v1_decision_proto_rawDescData
}

var file_openshield_v1_decision_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_openshield_v1_decision_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_openshield_v1_decision_proto_goTypes = []any{
	(Action)(0),                   // 0: openshield.v1.Action
	(*Decision)(nil),              // 1: openshield.v1.Decision
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_openshield_v1_decision_proto_depIdxs = []int32{
	0, // 0: openshield.v1.Decision.action:type_name -> openshield.v1.Action
	2, // 1: openshield.v1.Decision.decided_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_openshield_v1_decision_proto_init() }
func file_openshield_v1_decision_proto_init() {
	if File_openshield_v1_decision_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openshield_v1_decision_proto_rawDesc), len(file_openshield_v1_decision_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openshield_v1_decision_proto_goTypes,
		DependencyIndexes: file_openshield_v1_decision_proto_depIdxs,
		EnumInfos:         file_openshield_v1_decision_proto_enumTypes,
		MessageInfos:      file_openshield_v1_decision_proto_msgTypes,
	}.Build()
	File_openshield_v1_decision_proto = out.File
	file_openshield_v1_decision_proto_goTypes = nil
	file_openshield_v1_decision_proto_depIdxs = nil
}
