// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: openshield/v1/event.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Purpose declares why an Event was collected. Purpose limitation that depends
// on discipline is not purpose limitation, so this is a schema field and the
// policy engine refuses cross-purpose evaluation (D20).
type Purpose int32

const (
	Purpose_PURPOSE_UNSPECIFIED      Purpose = 0
	Purpose_PURPOSE_DLP              Purpose = 1
	Purpose_PURPOSE_INSIDER_RISK     Purpose = 2
	Purpose_PURPOSE_COMPLIANCE_AUDIT Purpose = 3
)

// Enum value maps for Purpose.
var (
	Purpose_name = map[int32]string{
		0: "PURPOSE_UNSPECIFIED",
		1: "PURPOSE_DLP",
		2: "PURPOSE_INSIDER_RISK",
		3: "PURPOSE_COMPLIANCE_AUDIT",
	}
	Purpose_value = map[string]int32{
		"PURPOSE_UNSPECIFIED":      0,
		"PURPOSE_DLP":              1,
		"PURPOSE_INSIDER_RISK":     2,
		"PURPOSE_COMPLIANCE_AUDIT": 3,
	}
)

func (x Purpose) Enum() *Purpose {
	p := new(Purpose)
	*p = x
	return p
}

func (x Purpose) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Purpose) Descriptor() protoreflect.EnumDescriptor {
	return file_openshield_v1_event_proto_enumTypes[0].Descriptor()
}

func (Purpose) Type() protoreflect.EnumType {
	return &file_openshield_v1_event_proto_enumTypes[0]
}

func (x Purpose) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Purpose.Descriptor instead.
func (Purpose) EnumDescriptor() ([]byte, []int) {
	return file_openshield_v1_event_proto_rawDescGZIP(), []int{0}
}

type EventKind int32

const (
	EventKind_EVENT_KIND_UNSPECIFIED   EventKind = 0
	EventKind_EVENT_KIND_FILE_OPENED   EventKind = 1
	EventKind_EVENT_KIND_FILE_MODIFIED EventKind = 2
	EventKind_EVENT_KIND_FILE_CREATED  EventKind = 3
	EventKind_EVENT_KIND_USB_INSERTED  EventKind = 4
	EventKind_EVENT_KIND_NETWORK_FLOW  EventKind = 5
	EventKind_EVENT_KIND_HTTP_REQUEST  EventKind = 6
	EventKind_EVENT_KIND_DNS_QUERY     EventKind = 7 // a resolved DNS question (Phase C — DNS breadth)
	EventKind_EVENT_KIND_SMTP_MESSAGE  EventKind = 8 // an outbound SMTP message (Phase C — email breadth)
)

// Enum value maps for EventKind.
var (
	EventKind_name = map[int32]string{
		0: "EVENT_KIND_UNSPECIFIED",
		1: "EVENT_KIND_FILE_OPENED",
		2: "EVENT_KIND_FILE_MODIFIED",
		3: "EVENT_KIND_FILE_CREATED",
		4: "EVENT_KIND_USB_INSERTED",
		5: "EVENT_KIND_NETWORK_FLOW",
		6: "EVENT_KIND_HTTP_REQUEST",
		7: "EVENT_KIND_DNS_QUERY",
		8: "EVENT_KIND_SMTP_MESSAGE",
	}
	EventKind_value = map[string]int32{
		"EVENT_KIND_UNSPECIFIED":   0,
		"EVENT_KIND_FILE_OPENED":   1,
		"EVENT_KIND_FILE_MODIFIED": 2,
		"EVENT_KIND_FILE_CREATED":  3,
		"EVENT_KIND_USB_INSERTED":  4,
		"EVENT_KIND_NETWORK_FLOW":  5,
		"EVENT_KIND_HTTP_REQUEST":  6,
		"EVENT_KIND_DNS_QUERY":     7,
		"EVENT_KIND_SMTP_MESSAGE":  8,
	}
)

func (x EventKind) Enum() *EventKind {
	p := new(EventKind)
	*p = x
	return p
}

func (x EventKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_openshield_v1_event_proto_enumTypes[1].Descriptor()
}

func (EventKind) Type() protoreflect.EnumType {
	return &file_openshield_v1_event_proto_enumTypes[1]
}

func (x EventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventKind.Descriptor instead.
func (EventKind) EnumDescriptor() ([]byte, []int) {
	return file_openshield_v1_event_proto_rawDescGZIP(), []int{1}
}

// NetworkDirection is which way a flow crosses the gateway.
type NetworkDirection int32

const (
	NetworkDirection_NETWORK_DIRECTION_UNSPECIFIED NetworkDirection = 0
	NetworkDirection_NETWORK_DIRECTION_EGRESS      NetworkDirection = 1
	NetworkDirection_NETWORK_DIRECTION_INGRESS     NetworkDirection = 2
)

// Enum value maps for NetworkDirection.
var (
	NetworkDirection_name = map[int32]string{
		0: "NETWORK_DIRECTION_UNSPECIFIED",
		1: "NETWORK_DIRECTION_EGRESS",
		2: "NETWORK_DIRECTION_INGRESS",
	}
	NetworkDirection_value = map[string]int32{
		"NETWORK_DIRECTION_UNSPECIFIED": 0,
		"NETWORK_DIRECTION_EGRESS":      1,
		"NETWORK_DIRECTION_INGRESS":     2,
	}
)

func (x NetworkDirection) Enum() *NetworkDirection {
	p := new(NetworkDirection)
	*p = x
	return p
}

func (x NetworkDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_openshield_v1_event_proto_enumTypes[2].Descriptor()
}

func (NetworkDirection) Type() protoreflect.EnumType {
	return &file_openshield_v1_event_proto_enumTypes[2]
}

func (x NetworkDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkDirection.Descriptor instead.
func (NetworkDirection) EnumDescriptor() ([]byte, []int) {
	return file_openshield_v1_event_proto_rawDescGZIP(), []int{2}
}

// Subject identifies WHO, pseudonymously. The mapping to a real identity lives
// outside the event stream behind an audited lookup — the event stream is the
// most widely copied, retained and queried artefact in the system (D23).
type Subject struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PseudonymousId string                 `protobuf:"bytes,1,opt,name=pseudonymous_id,json=pseudonymousId,proto3" json:"pseudonymous_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Subject) Reset() {
	*x = Subject{}
	mi := &file_openshield_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subject) ProtoMessage() {}

func (x *Subject) ProtoReflect() protoreflect.Message {
	mi := &file_openshield_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subject.ProtoReflect.Descriptor instead.
func (*Subject) Descriptor() ([]byte, []int) {
	return file_openshield_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *Subject) GetPseudonymousId() string {
	if x != nil {
		return x.PseudonymousId
	}
	return ""
}

// ParentAndName is fanotify's DFID_NAME shape: a parent-directory handle plus a
// filename. The name costs no capability; a name is not a path.
type ParentAndName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentHandle  []byte                 `protobuf:"bytes,1,opt,name=parent_handle,json=parentHandle,proto3" json:"parent_handle,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParentAndName) Reset() {
	*x = ParentAndName{}
	mi := &file_openshield_v1_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParentAndName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParentAndName) ProtoMessage() {}

func (x *ParentAndName) ProtoReflect() protoreflect.Message {
	mi := &file_openshield_v1_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParentAndName.ProtoReflect.Descriptor instead.
func (*ParentAndName) Descriptor() ([]byte, []int) {
	return file_openshield_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *ParentAndName) GetParentHandle() []byte {
	if x != nil {
		return x.ParentHandle
	}
	return nil
}

func (x *ParentAndName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// FilesystemSubject carries the three identity forms T-005 measured. Which one
// arrives follows from the coverage mode the agent selects, not from chance.
// See docs/spike-t005-fanotify.md.
type FilesystemSubject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identity:
	//
	//	*FilesystemSubject_ResolvedPath
	//	*FilesystemSubject_FileHandle
	//	*FilesystemSubject_ParentAndName
	Identity      isFilesystemSubject_Identity `protobuf_oneof:"identity"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesystemSubject) Reset() {
	*x = FilesystemSubject{}
	mi := &file_openshield_v1_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesystemSubject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesystemSubject) ProtoMessage() {}

func (x *FilesystemSubject) ProtoReflect() protoreflect.Message {
	mi := &file_openshield_v1_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesystemSubject.ProtoReflect.Descriptor instead.
func (*FilesystemSubject) Descriptor() ([]byte, []int) {
	return file_openshield_v1_event_proto_rawDescGZIP(), []int{2}
}

func (x *FilesystemSubject) GetIdentity() isFilesystemSubject_Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *FilesystemSubject) GetResolvedPath() string {
	if x != nil {
		if x, ok := x.Identity.(*FilesystemSubject_ResolvedPath); ok {
			return x.ResolvedPath
		}
	}
	return ""
}

func (x *FilesystemSubject) GetFileHandle() []byte {
	if x != nil {
		if x, ok := x.Identity.(*FilesystemSubject_FileHandle); ok {
			return x.FileHandle
		}
	}
	return nil
}

func (x *FilesystemSubject) GetParentAndName() *ParentAndName {
	if x != nil {
		if x, ok := x.Identity.(*FilesystemSubject_ParentAndName); ok {
			return x.ParentAndName
		}
	}
	return nil
}

type isFilesystemSubject_Identity interface {
	isFilesystemSubject_Identity()
}

type FilesystemSubject_ResolvedPath struct {
	// Classic mode: kernel supplies an fd, path follows from readlink.
	ResolvedPath string `protobuf:"bytes,1,opt,name=resolved_path,json=resolvedPath,proto3,oneof"`
}

type FilesystemSubject_FileHandle struct {
	// FID mode (FAN_MARK_FILESYSTEM): opaque; resolving needs CAP_DAC_READ_SEARCH.
	FileHandle []byte `protobuf:"bytes,2,opt,name=file_handle,json=fileHandle,proto3,oneof"`
}

type FilesystemSubject_ParentAndName struct {
	// DFID_NAME mode: parent handle + filename.
	ParentAndName *ParentAndName `protobuf:"bytes,3,opt,name=parent_and_name,json=parentAndName,proto3,oneof"`
}

func (*FilesystemSubject_ResolvedPath) isFilesystemSubject_Identity() {}

func (*FilesystemSubject_FileHandle) isFilesystemSubject_Identity() {}

func (*FilesystemSubject_ParentAndName) isFilesystemSubject_Identity() {}

type UsbSubject struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	VendorId        string                 `protobuf:"bytes,1,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	ProductId       string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SerialPseudonym string                 `protobuf:"bytes,3,opt,name=serial_pseudonym,json=serialPseudonym,proto3" json:"serial_pseudonym,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UsbSubject) Reset() {
	*x = UsbSubject{}
	mi := &file_openshield_v1_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsbSubject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsbSubject) ProtoMessage() {}

func (x *UsbSubject) ProtoReflect() protoreflect.Message {
	mi := &file_openshield_v1_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsbSubject.ProtoReflect.Descriptor instead.
func (*UsbSubject) Descriptor() ([]byte, []int) {
	return file_openshield_v1_event_proto_rawDescGZIP(), []int{3}
}

func (x *UsbSubject) GetVendorId() string {
	if x != nil {
		return x.VendorId
	}
	return ""
}

func (x *UsbSubject) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UsbSubject) GetSerialPseudonym() string {
	if x != nil {
		return x.SerialPseudonym
	}
	return ""
}

// NetworkSubject is a network flow or L7 request the gateway observed (N1/D69).
// It carries connection/request METADATA ONLY — never the body content, which is
// classified in the gateway PROCESS and never leaves it (D10/D29), exactly as
// file content stays in the worker. flow_id is an opaque handle into the
// gateway's live flow table: the network analogue of a file path, what a flow
// enforcer resolves to a live connection to act on.
type NetworkSubject struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	FlowId   string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	SrcIp    string                 `protobuf:"bytes,2,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	SrcPort  uint32                 `protobuf:"varint,3,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstIp    string                 `protobuf:"bytes,4,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	DstPort  uint32                 `protobuf:"varint,5,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	Protocol string                 `protobuf:"bytes,6,opt,name=protocol,proto3" json:"protocol,omitempty"` // tcp | udp | ...
	// L7 metadata, present when the gateway terminates TLS / sees plaintext. This
	// is METADATA (a policy decides on it), NOT the body.
	SniHost       string           `protobuf:"bytes,7,opt,name=sni_host,json=sniHost,proto3" json:"sni_host,omitempty"` // TLS SNI / HTTP Host
	HttpMethod    string           `protobuf:"bytes,8,opt,name=http_method,json=httpMethod,proto3" json:"http_method,omitempty"`
	HttpPath      string           `protobuf:"bytes,9,opt,name=http_path,json=httpPath,proto3" json:"http_path,omitempty"`
	Direction     NetworkDirection `protobuf:"varint,10,opt,name=direction,proto3,enum=openshield.v1.NetworkDirection" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkSubject) Reset() {
	*x = NetworkSubject{}
	mi := &file_openshield_v1_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkSubject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkSubject) ProtoMessage() {}

func (x *NetworkSubject) ProtoReflect() protoreflect.Message {
	mi := &file_openshield_v1_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkSubject.ProtoReflect.Descriptor instead.
func (*NetworkSubject) Descriptor() ([]byte, []int) {
	return file_openshield_v1_event_proto_rawDescGZIP(), []int{4}
}

func (x *NetworkSubject) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *NetworkSubject) GetSrcIp() string {
	if x != nil {
		return x.SrcIp
	}
	return ""
}

func (x *NetworkSubject) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *NetworkSubject) GetDstIp() string {
	if x != nil {
		return x.DstIp
	}
	return ""
}

func (x *NetworkSubject) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *NetworkSubject) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *NetworkSubject) GetSniHost() string {
	if x != nil {
		return x.SniHost
	}
	return ""
}

func (x *NetworkSubject) GetHttpMethod() string {
	if x != nil {
		return x.HttpMethod
	}
	return ""
}

func (x *NetworkSubject) GetHttpPath() string {
	if x != nil {
		return x.HttpPath
	}
	return ""
}

func (x *NetworkSubject) GetDirection() NetworkDirection {
	if x != nil {
		return x.Direction
	}
	return NetworkDirection_NETWORK_DIRECTION_UNSPECIFIED
}

// Event is what a producer emits. It carries metadata and references only —
// never file content (D10).
type Event struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	EventId     string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	AgentId     string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ConnectorId string                 `protobuf:"bytes,3,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"`
	// Monotonic per agent. Gaps must be detectable: an audit trail that cannot
	// reveal suppression is not evidentiary.
	Sequence   uint64                 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ObservedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	Subject    *Subject               `protobuf:"bytes,6,opt,name=subject,proto3" json:"subject,omitempty"`
	Purpose    Purpose                `protobuf:"varint,7,opt,name=purpose,proto3,enum=openshield.v1.Purpose" json:"purpose,omitempty"`
	Kind       EventKind              `protobuf:"varint,8,opt,name=kind,proto3,enum=openshield.v1.EventKind" json:"kind,omitempty"`
	// Types that are valid to be assigned to Target:
	//
	//	*Event_Filesystem
	//	*Event_Usb
	//	*Event_Network
	Target        isEvent_Target `protobuf_oneof:"target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_openshield_v1_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_openshield_v1_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_openshield_v1_event_proto_rawDescGZIP(), []int{5}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Event) GetConnectorId() string {
	if x != nil {
		return x.ConnectorId
	}
	return ""
}

func (x *Event) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Event) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *Event) GetSubject() *Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *Event) GetPurpose() Purpose {
	if x != nil {
		return x.Purpose
	}
	return Purpose_PURPOSE_UNSPECIFIED
}

func (x *Event) GetKind() EventKind {
	if x != nil {
		return x.Kind
	}
	return EventKind_EVENT_KIND_UNSPECIFIED
}

func (x *Event) GetTarget() isEvent_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *Event) GetFilesystem() *FilesystemSubject {
	if x != nil {
		if x, ok := x.Target.(*Event_Filesystem); ok {
			return x.Filesystem
		}
	}
	return nil
}

func (x *Event) GetUsb() *UsbSubject {
	if x != nil {
		if x, ok := x.Target.(*Event_Usb); ok {
			return x.Usb
		}
	}
	return nil
}

func (x *Event) GetNetwork() *NetworkSubject {
	if x != nil {
		if x, ok := x.Target.(*Event_Network); ok {
			return x.Network
		}
	}
	return nil
}

type isEvent_Target interface {
	isEvent_Target()
}

type Event_Filesystem struct {
	Filesystem *FilesystemSubject `protobuf:"bytes,9,opt,name=filesystem,proto3,oneof"`
}

type Event_Usb struct {
	Usb *UsbSubject `protobuf:"bytes,10,opt,name=usb,proto3,oneof"`
}

type Event_Network struct {
	Network *NetworkSubject `protobuf:"bytes,11,opt,name=network,proto3,oneof"`
}

func (*Event_Filesystem) isEvent_Target() {}

func (*Event_Usb) isEvent_Target() {}

func (*Event_Network) isEvent_Target() {}

var File_openshield_v1_event_proto protoreflect.FileDescriptor

const file_openshield_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x19openshield/v1/event.proto\x12\ropenshield.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"2\n" +
	"\aSubject\x12'\n" +
	"\x0fpseudonymous_id\x18\x01 \x01(\tR\x0epseudonymousId\"H\n" +
	"\rParentAndName\x12#\n" +
	"\rparent_handle\x18\x01 \x01(\fR\fparentHandle\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xb1\x01\n" +
	"\x11FilesystemSubject\x12%\n" +
	"\rresolved_path\x18\x01 \x01(\tH\x00R\fresolvedPath\x12!\n" +
	"\vfile_handle\x18\x02 \x01(\fH\x00R\n" +
	"fileHandle\x12F\n" +
	"\x0fparent_and_name\x18\x03 \x01(\v2\x1c.openshield.v1.ParentAndNameH\x00R\rparentAndNameB\n" +
	"\n" +
	"\bidentity\"s\n" +
	"\n" +
	"UsbSubject\x12\x1b\n" +
	"\tvendor_id\x18\x01 \x01(\tR\bvendorId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12)\n" +
	"\x10serial_pseudonym\x18\x03 \x01(\tR\x0fserialPseudonym\"\xc1\x02\n" +
	"\x0eNetworkSubject\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowId\x12\x15\n" +
	"\x06src_ip\x18\x02 \x01(\tR\x05srcIp\x12\x19\n" +
	"\bsrc_port\x18\x03 \x01(\rR\asrcPort\x12\x15\n" +
	"\x06dst_ip\x18\x04 \x01(\tR\x05dstIp\x12\x19\n" +
	"\bdst_port\x18\x05 \x01(\rR\adstPort\x12\x1a\n" +
	"\bprotocol\x18\x06 \x01(\tR\bprotocol\x12\x19\n" +
	"\bsni_host\x18\a \x01(\tR\asniHost\x12\x1f\n" +
	"\vhttp_method\x18\b \x01(\tR\n" +
	"httpMethod\x12\x1b\n" +
	"\thttp_path\x18\t \x01(\tR\bhttpPath\x12=\n" +
	"\tdirection\x18\n" +
	" \x01(\x0e2\x1f.openshield.v1.NetworkDirectionR\tdirection\"\x83\x04\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12!\n" +
	"\fconnector_id\x18\x03 \x01(\tR\vconnectorId\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x04R\bsequence\x12;\n" +
	"\vobserved_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x120\n" +
	"\asubject\x18\x06 \x01(\v2\x16.openshield.v1.SubjectR\asubject\x120\n" +
	"\apurpose\x18\a \x01(\x0e2\x16.openshield.v1.PurposeR\apurpose\x12,\n" +
	"\x04kind\x18\b \x01(\x0e2\x18.openshield.v1.EventKindR\x04kind\x12B\n" +
	"\n" +
	"filesystem\x18\t \x01(\v2 .openshield.v1.FilesystemSubjectH\x00R\n" +
	"filesystem\x12-\n" +
	"\x03usb\x18\n" +
	" \x01(\v2\x19.openshield.v1.UsbSubjectH\x00R\x03usb\x129\n" +
	"\anetwork\x18\v \x01(\v2\x1d.openshield.v1.NetworkSubjectH\x00R\anetworkB\b\n" +
	"\x06target*k\n" +
	"\aPurpose\x12\x17\n" +
	"\x13PURPOSE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vPURPOSE_DLP\x10\x01\x12\x18\n" +
	"\x14PURPOSE_INSIDER_RISK\x10\x02\x12\x1c\n" +
	"\x18PURPOSE_COMPLIANCE_AUDIT\x10\x03*\x8c\x02\n" +
	"\tEventKind\x12\x1a\n" +
	"\x16EVENT_KIND_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16EVENT_KIND_FILE_OPENED\x10\x01\x12\x1c\n" +
	"\x18EVENT_KIND_FILE_MODIFIED\x10\x02\x12\x1b\n" +
	"\x17EVENT_KIND_FILE_CREATED\x10\x03\x12\x1b\n" +
	"\x17EVENT_KIND_USB_INSERTED\x10\x04\x12\x1b\n" +
	"\x17EVENT_KIND_NETWORK_FLOW\x10\x05\x12\x1b\n" +
	"\x17EVENT_KIND_HTTP_REQUEST\x10\x06\x12\x18\n" +
	"\x14EVENT_KIND_DNS_QUERY\x10\a\x12\x1b\n" +
	"\x17EVENT_KIND_SMTP_MESSAGE\x10\b*r\n" +
	"\x10NetworkDirection\x12!\n" +
	"\x1dNETWORK_DIRECTION_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18NETWORK_DIRECTION_EGRESS\x10\x01\x12\x1d\n" +
	"\x19NETWORK_DIRECTION_INGRESS\x10\x02B@Z>github.com/lucianoengel/openshield/internal/core/corev1;corev1b\x06proto3"

var (
	file_openshield_v1_event_proto_rawDescOnce sync.Once
	file_openshield_v1_event_proto_rawDescData []byte
)

func file_openshield_v1_event_proto_rawDescGZIP() []byte {
	file_openshield_v1_event_proto_rawDescOnce.Do(func() {
		file_openshield_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openshield_v1_event_proto_rawDesc), len(file_openshield_v1_event_proto_rawDesc)))
	})
	return file_openshield_v1_event_proto_rawDescData
}

var file_openshield_v1_event_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_openshield_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_openshield_v1_event_proto_goTypes = []any{
	(Purpose)(0),                  // 0: openshield.v1.Purpose
	(EventKind)(0),                // 1: openshield.v1.EventKind
	(NetworkDirection)(0),         // 2: openshield.v1.NetworkDirection
	(*Subject)(nil),               // 3: openshield.v1.Subject
	(*ParentAndName)(nil),         // 4: openshield.v1.ParentAndName
	(*FilesystemSubject)(nil),     // 5: openshield.v1.FilesystemSubject
	(*UsbSubject)(nil),            // 6: openshield.v1.UsbSubject
	(*NetworkSubject)(nil),        // 7: openshield.v1.NetworkSubject
	(*Event)(nil),                 // 8: openshield.v1.Event
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_openshield_v1_event_proto_depIdxs = []int32{
	4, // 0: openshield.v1.FilesystemSubject.parent_and_name:type_name -> openshield.v1.ParentAndName
	2, // 1: openshield.v1.NetworkSubject.direction:type_name -> openshield.v1.NetworkDirection
	9, // 2: openshield.v1.Event.observed_at:type_name -> google.protobuf.Timestamp
	3, // 3: openshield.v1.Event.subject:type_name -> openshield.v1.Subject
	0, // 4: openshield.v1.Event.purpose:type_name -> openshield.v1.Purpose
	1, // 5: openshield.v1.Event.kind:type_name -> openshield.v1.EventKind
	5, // 6: openshield.v1.Event.filesystem:type_name -> openshield.v1.FilesystemSubject
	6, // 7: openshield.v1.Event.usb:type_name -> openshield.v1.UsbSubject
	7, // 8: openshield.v1.Event.network:type_name -> openshield.v1.NetworkSubject
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_openshield_v1_event_proto_init() }
func file_openshield_v1_event_proto_init() {
	if File_openshield_v1_event_proto != nil {
		return
	}
	file_openshield_v1_event_proto_msgTypes[2].OneofWrappers = []any{
		(*FilesystemSubject_ResolvedPath)(nil),
		(*FilesystemSubject_FileHandle)(nil),
		(*FilesystemSubject_ParentAndName)(nil),
	}
	file_openshield_v1_event_proto_msgTypes[5].OneofWrappers = []any{
		(*Event_Filesystem)(nil),
		(*Event_Usb)(nil),
		(*Event_Network)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openshield_v1_event_proto_rawDesc), len(file_openshield_v1_event_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openshield_v1_event_proto_goTypes,
		DependencyIndexes: file_openshield_v1_event_proto_depIdxs,
		EnumInfos:         file_openshield_v1_event_proto_enumTypes,
		MessageInfos:      file_openshield_v1_event_proto_msgTypes,
	}.Build()
	File_openshield_v1_event_proto = out.File
	file_openshield_v1_event_proto_goTypes = nil
	file_openshield_v1_event_proto_depIdxs = nil
}
