// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: openshield/v1/heartbeat.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Heartbeat is the agent's "I am still here" signal (T-018).
//
// It carries no telemetry — only enough to update the control plane's "last
// seen" for a host, so that the ABSENCE of an agent becomes detectable. This is
// what backs the honest claim (D16): tamper-DETECTION, not prevention. A host
// that should be reporting and goes silent is the signal a dead-man's-switch
// raises.
//
// Sequence is monotonic per agent so a gap is visible; a suppressed heartbeat
// is not a substitute for the agent being gone, but a gap is one more sign.
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_openshield_v1_heartbeat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_openshield_v1_heartbeat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_openshield_v1_heartbeat_proto_rawDescGZIP(), []int{0}
}

func (x *Heartbeat) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Heartbeat) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Heartbeat) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

var File_openshield_v1_heartbeat_proto protoreflect.FileDescriptor

const file_openshield_v1_heartbeat_proto_rawDesc = "" +
	"\n" +
	"\x1dopenshield/v1/heartbeat.proto\x12\ropenshield.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x7f\n" +
	"\tHeartbeat\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12;\n" +
	"\vobserved_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAtB@Z>github.com/lucianoengel/openshield/internal/core/corev1;corev1b\x06proto3"

var (
	file_openshield_v1_heartbeat_proto_rawDescOnce sync.Once
	file_openshield_v1_heartbeat_proto_rawDescData []byte
)

func file_openshield_v1_heartbeat_proto_rawDescGZIP() []byte {
	file_openshield_v1_heartbeat_proto_rawDescOnce.Do(func() {
		file_openshield_v1_heartbeat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openshield_v1_heartbeat_proto_rawDesc), len(file_openshield_v1_heartbeat_proto_rawDesc)))
	})
	return file_openshield_v1_heartbeat_proto_rawDescData
}

var file_openshield_v1_heartbeat_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_openshield_v1_heartbeat_proto_goTypes = []any{
	(*Heartbeat)(nil),             // 0: openshield.v1.Heartbeat
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_openshield_v1_heartbeat_proto_depIdxs = []int32{
	1, // 0: openshield.v1.Heartbeat.observed_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_openshield_v1_heartbeat_proto_init() }
func file_openshield_v1_heartbeat_proto_init() {
	if File_openshield_v1_heartbeat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openshield_v1_heartbeat_proto_rawDesc), len(file_openshield_v1_heartbeat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openshield_v1_heartbeat_proto_goTypes,
		DependencyIndexes: file_openshield_v1_heartbeat_proto_depIdxs,
		MessageInfos:      file_openshield_v1_heartbeat_proto_msgTypes,
	}.Build()
	File_openshield_v1_heartbeat_proto = out.File
	file_openshield_v1_heartbeat_proto_goTypes = nil
	file_openshield_v1_heartbeat_proto_depIdxs = nil
}
