// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: openshield/v1/ipc.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClassifyRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	EventId   string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// What to classify. The worker opens this itself, with its own (unprivileged)
	// credentials — the privileged process does not read the file and hand bytes
	// over, because that would put attacker-controlled content in its address
	// space, which is the thing being prevented.
	//
	// Types that are valid to be assigned to Subject:
	//
	//	*ClassifyRequest_Path
	//	*ClassifyRequest_FileHandle
	//	*ClassifyRequest_Content
	Subject isClassifyRequest_Subject `protobuf_oneof:"subject"`
	// Hard ceiling on bytes the worker may read. A decompression bomb must hit a
	// limit rather than exhaust memory.
	MaxBytes      uint64 `protobuf:"varint,5,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyRequest) Reset() {
	*x = ClassifyRequest{}
	mi := &file_openshield_v1_ipc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyRequest) ProtoMessage() {}

func (x *ClassifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openshield_v1_ipc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyRequest.ProtoReflect.Descriptor instead.
func (*ClassifyRequest) Descriptor() ([]byte, []int) {
	return file_openshield_v1_ipc_proto_rawDescGZIP(), []int{0}
}

func (x *ClassifyRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ClassifyRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ClassifyRequest) GetSubject() isClassifyRequest_Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *ClassifyRequest) GetPath() string {
	if x != nil {
		if x, ok := x.Subject.(*ClassifyRequest_Path); ok {
			return x.Path
		}
	}
	return ""
}

func (x *ClassifyRequest) GetFileHandle() []byte {
	if x != nil {
		if x, ok := x.Subject.(*ClassifyRequest_FileHandle); ok {
			return x.FileHandle
		}
	}
	return nil
}

func (x *ClassifyRequest) GetContent() []byte {
	if x != nil {
		if x, ok := x.Subject.(*ClassifyRequest_Content); ok {
			return x.Content
		}
	}
	return nil
}

func (x *ClassifyRequest) GetMaxBytes() uint64 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

type isClassifyRequest_Subject interface {
	isClassifyRequest_Subject()
}

type ClassifyRequest_Path struct {
	Path string `protobuf:"bytes,3,opt,name=path,proto3,oneof"`
}

type ClassifyRequest_FileHandle struct {
	FileHandle []byte `protobuf:"bytes,4,opt,name=file_handle,json=fileHandle,proto3,oneof"`
}

type ClassifyRequest_Content struct {
	// Inline bytes the CALLER already holds. Used by a network-capable node (the
	// gateway) that must hold the body to proxy it: handing the bytes here moves
	// the PARSER (the RCE surface) into the sandboxed worker rather than running
	// it in the process holding the network sockets (D71). The path-only rule —
	// the worker opens the file itself so the CAP_SYS_ADMIN agent never holds
	// bytes — is the AGENT's discipline, not the proto's.
	Content []byte `protobuf:"bytes,6,opt,name=content,proto3,oneof"`
}

func (*ClassifyRequest_Path) isClassifyRequest_Subject() {}

func (*ClassifyRequest_FileHandle) isClassifyRequest_Subject() {}

func (*ClassifyRequest_Content) isClassifyRequest_Subject() {}

type DetectorHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DetectorType  DetectorType           `protobuf:"varint,1,opt,name=detector_type,json=detectorType,proto3,enum=openshield.v1.DetectorType" json:"detector_type,omitempty"`
	Confidence    float64                `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Count         uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectorHit) Reset() {
	*x = DetectorHit{}
	mi := &file_openshield_v1_ipc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectorHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectorHit) ProtoMessage() {}

func (x *DetectorHit) ProtoReflect() protoreflect.Message {
	mi := &file_openshield_v1_ipc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectorHit.ProtoReflect.Descriptor instead.
func (*DetectorHit) Descriptor() ([]byte, []int) {
	return file_openshield_v1_ipc_proto_rawDescGZIP(), []int{1}
}

func (x *DetectorHit) GetDetectorType() DetectorType {
	if x != nil {
		return x.DetectorType
	}
	return DetectorType_DETECTOR_TYPE_UNSPECIFIED
}

func (x *DetectorHit) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *DetectorHit) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ClassifyResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	EventId   string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Hits      []*DetectorHit         `protobuf:"bytes,3,rep,name=hits,proto3" json:"hits,omitempty"`
	// Set when the worker could not classify. An error is not "nothing found":
	// conflating them would let a crashing parser read as a clean file.
	Error     string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Truncated bool   `protobuf:"varint,5,opt,name=truncated,proto3" json:"truncated,omitempty"`
	// Content-signature hits (NIPS-2) from matching the operator ruleset against the
	// body IN THE WORKER. Each carries the rule id + category + confidence — never
	// the matched bytes, so the crossing stays content-free (D10), same discipline
	// as DetectorHit.
	ThreatMatches []*ThreatMatch `protobuf:"bytes,6,rep,name=threat_matches,json=threatMatches,proto3" json:"threat_matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyResponse) Reset() {
	*x = ClassifyResponse{}
	mi := &file_openshield_v1_ipc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyResponse) ProtoMessage() {}

func (x *ClassifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openshield_v1_ipc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyResponse.ProtoReflect.Descriptor instead.
func (*ClassifyResponse) Descriptor() ([]byte, []int) {
	return file_openshield_v1_ipc_proto_rawDescGZIP(), []int{2}
}

func (x *ClassifyResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ClassifyResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ClassifyResponse) GetHits() []*DetectorHit {
	if x != nil {
		return x.Hits
	}
	return nil
}

func (x *ClassifyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ClassifyResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *ClassifyResponse) GetThreatMatches() []*ThreatMatch {
	if x != nil {
		return x.ThreatMatches
	}
	return nil
}

var File_openshield_v1_ipc_proto protoreflect.FileDescriptor

const file_openshield_v1_ipc_proto_rawDesc = "" +
	"\n" +
	"\x17openshield/v1/ipc.proto\x12\ropenshield.v1\x1a\"openshield/v1/classification.proto\x1a\x1aopenshield/v1/threat.proto\"\xc8\x01\n" +
	"\x0fClassifyRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x14\n" +
	"\x04path\x18\x03 \x01(\tH\x00R\x04path\x12!\n" +
	"\vfile_handle\x18\x04 \x01(\fH\x00R\n" +
	"fileHandle\x12\x1a\n" +
	"\acontent\x18\x06 \x01(\fH\x00R\acontent\x12\x1b\n" +
	"\tmax_bytes\x18\x05 \x01(\x04R\bmaxBytesB\t\n" +
	"\asubject\"\x85\x01\n" +
	"\vDetectorHit\x12@\n" +
	"\rdetector_type\x18\x01 \x01(\x0e2\x1b.openshield.v1.DetectorTypeR\fdetectorType\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01R\n" +
	"confidence\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\"\xf3\x01\n" +
	"\x10ClassifyResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12.\n" +
	"\x04hits\x18\x03 \x03(\v2\x1a.openshield.v1.DetectorHitR\x04hits\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1c\n" +
	"\ttruncated\x18\x05 \x01(\bR\ttruncated\x12A\n" +
	"\x0ethreat_matches\x18\x06 \x03(\v2\x1a.openshield.v1.ThreatMatchR\rthreatMatchesB@Z>github.com/lucianoengel/openshield/internal/core/corev1;corev1b\x06proto3"

var (
	file_openshield_v1_ipc_proto_rawDescOnce sync.Once
	file_openshield_v1_ipc_proto_rawDescData []byte
)

func file_openshield_v1_ipc_proto_rawDescGZIP() []byte {
	file_openshield_v1_ipc_proto_rawDescOnce.Do(func() {
		file_openshield_v1_ipc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openshield_v1_ipc_proto_rawDesc), len(file_openshield_v1_ipc_proto_rawDesc)))
	})
	return file_openshield_v1_ipc_proto_rawDescData
}

var file_openshield_v1_ipc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_openshield_v1_ipc_proto_goTypes = []any{
	(*ClassifyRequest)(nil),  // 0: openshield.v1.ClassifyRequest
	(*DetectorHit)(nil),      // 1: openshield.v1.DetectorHit
	(*ClassifyResponse)(nil), // 2: openshield.v1.ClassifyResponse
	(DetectorType)(0),        // 3: openshield.v1.DetectorType
	(*ThreatMatch)(nil),      // 4: openshield.v1.ThreatMatch
}
var file_openshield_v1_ipc_proto_depIdxs = []int32{
	3, // 0: openshield.v1.DetectorHit.detector_type:type_name -> openshield.v1.DetectorType
	1, // 1: openshield.v1.ClassifyResponse.hits:type_name -> openshield.v1.DetectorHit
	4, // 2: openshield.v1.ClassifyResponse.threat_matches:type_name -> openshield.v1.ThreatMatch
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_openshield_v1_ipc_proto_init() }
func file_openshield_v1_ipc_proto_init() {
	if File_openshield_v1_ipc_proto != nil {
		return
	}
	file_openshield_v1_classification_proto_init()
	file_openshield_v1_threat_proto_init()
	file_openshield_v1_ipc_proto_msgTypes[0].OneofWrappers = []any{
		(*ClassifyRequest_Path)(nil),
		(*ClassifyRequest_FileHandle)(nil),
		(*ClassifyRequest_Content)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openshield_v1_ipc_proto_rawDesc), len(file_openshield_v1_ipc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openshield_v1_ipc_proto_goTypes,
		DependencyIndexes: file_openshield_v1_ipc_proto_depIdxs,
		MessageInfos:      file_openshield_v1_ipc_proto_msgTypes,
	}.Build()
	File_openshield_v1_ipc_proto = out.File
	file_openshield_v1_ipc_proto_goTypes = nil
	file_openshield_v1_ipc_proto_depIdxs = nil
}
