// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: openshield/v1/posture.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PostureUpdate reports a device's compliance state to the gateway (D92), so the
// access policy can require an attested, compliant device (D85). The endpoint agent
// knows its own device state and reports it (the report side is a follow-up); the
// gateway reads it into its PostureStore and the LOCAL policy decides. A device with
// NO posture published is UNTRUSTED — the D85 tamper-lockout: a killed/tampered
// endpoint reports no posture and is denied. The subject is pseudonymous (D23).
type PostureUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Compliant     bool                   `protobuf:"varint,2,opt,name=compliant,proto3" json:"compliant,omitempty"`
	DiskEncrypted bool                   `protobuf:"varint,3,opt,name=disk_encrypted,json=diskEncrypted,proto3" json:"disk_encrypted,omitempty"`
	AgentPresent  bool                   `protobuf:"varint,4,opt,name=agent_present,json=agentPresent,proto3" json:"agent_present,omitempty"`
	OsPatchTier   int32                  `protobuf:"varint,5,opt,name=os_patch_tier,json=osPatchTier,proto3" json:"os_patch_tier,omitempty"` // matches core.PatchTier
	ComputedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=computed_at,json=computedAt,proto3" json:"computed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostureUpdate) Reset() {
	*x = PostureUpdate{}
	mi := &file_openshield_v1_posture_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostureUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostureUpdate) ProtoMessage() {}

func (x *PostureUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_openshield_v1_posture_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostureUpdate.ProtoReflect.Descriptor instead.
func (*PostureUpdate) Descriptor() ([]byte, []int) {
	return file_openshield_v1_posture_proto_rawDescGZIP(), []int{0}
}

func (x *PostureUpdate) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *PostureUpdate) GetCompliant() bool {
	if x != nil {
		return x.Compliant
	}
	return false
}

func (x *PostureUpdate) GetDiskEncrypted() bool {
	if x != nil {
		return x.DiskEncrypted
	}
	return false
}

func (x *PostureUpdate) GetAgentPresent() bool {
	if x != nil {
		return x.AgentPresent
	}
	return false
}

func (x *PostureUpdate) GetOsPatchTier() int32 {
	if x != nil {
		return x.OsPatchTier
	}
	return 0
}

func (x *PostureUpdate) GetComputedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ComputedAt
	}
	return nil
}

var File_openshield_v1_posture_proto protoreflect.FileDescriptor

const file_openshield_v1_posture_proto_rawDesc = "" +
	"\n" +
	"\x1bopenshield/v1/posture.proto\x12\ropenshield.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf4\x01\n" +
	"\rPostureUpdate\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1c\n" +
	"\tcompliant\x18\x02 \x01(\bR\tcompliant\x12%\n" +
	"\x0edisk_encrypted\x18\x03 \x01(\bR\rdiskEncrypted\x12#\n" +
	"\ragent_present\x18\x04 \x01(\bR\fagentPresent\x12\"\n" +
	"\ros_patch_tier\x18\x05 \x01(\x05R\vosPatchTier\x12;\n" +
	"\vcomputed_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"computedAtB@Z>github.com/lucianoengel/openshield/internal/core/corev1;corev1b\x06proto3"

var (
	file_openshield_v1_posture_proto_rawDescOnce sync.Once
	file_openshield_v1_posture_proto_rawDescData []byte
)

func file_openshield_v1_posture_proto_rawDescGZIP() []byte {
	file_openshield_v1_posture_proto_rawDescOnce.Do(func() {
		file_openshield_v1_posture_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openshield_v1_posture_proto_rawDesc), len(file_openshield_v1_posture_proto_rawDesc)))
	})
	return file_openshield_v1_posture_proto_rawDescData
}

var file_openshield_v1_posture_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_openshield_v1_posture_proto_goTypes = []any{
	(*PostureUpdate)(nil),         // 0: openshield.v1.PostureUpdate
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_openshield_v1_posture_proto_depIdxs = []int32{
	1, // 0: openshield.v1.PostureUpdate.computed_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_openshield_v1_posture_proto_init() }
func file_openshield_v1_posture_proto_init() {
	if File_openshield_v1_posture_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openshield_v1_posture_proto_rawDesc), len(file_openshield_v1_posture_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openshield_v1_posture_proto_goTypes,
		DependencyIndexes: file_openshield_v1_posture_proto_depIdxs,
		MessageInfos:      file_openshield_v1_posture_proto_msgTypes,
	}.Build()
	File_openshield_v1_posture_proto = out.File
	file_openshield_v1_posture_proto_goTypes = nil
	file_openshield_v1_posture_proto_depIdxs = nil
}
