// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: openshield/v1/risk.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RiskUpdate is the control plane telling the gateway a subject's current risk
// (D91, the T2 continuous-verification loop). The server PUBLISHES it; the gateway
// READS it into its RiskStore and the LOCAL policy decides (D89) — the server informs,
// the gateway decides, the server never commands. The subject is pseudonymous (D23);
// this carries no content, only a fleet-level risk signal.
type RiskUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	RiskScore     float64                `protobuf:"fixed64,2,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"` // [0,1]
	ComputedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=computed_at,json=computedAt,proto3" json:"computed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskUpdate) Reset() {
	*x = RiskUpdate{}
	mi := &file_openshield_v1_risk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskUpdate) ProtoMessage() {}

func (x *RiskUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_openshield_v1_risk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskUpdate.ProtoReflect.Descriptor instead.
func (*RiskUpdate) Descriptor() ([]byte, []int) {
	return file_openshield_v1_risk_proto_rawDescGZIP(), []int{0}
}

func (x *RiskUpdate) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *RiskUpdate) GetRiskScore() float64 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *RiskUpdate) GetComputedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ComputedAt
	}
	return nil
}

var File_openshield_v1_risk_proto protoreflect.FileDescriptor

const file_openshield_v1_risk_proto_rawDesc = "" +
	"\n" +
	"\x18openshield/v1/risk.proto\x12\ropenshield.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x82\x01\n" +
	"\n" +
	"RiskUpdate\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x02 \x01(\x01R\triskScore\x12;\n" +
	"\vcomputed_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"computedAtB@Z>github.com/lucianoengel/openshield/internal/core/corev1;corev1b\x06proto3"

var (
	file_openshield_v1_risk_proto_rawDescOnce sync.Once
	file_openshield_v1_risk_proto_rawDescData []byte
)

func file_openshield_v1_risk_proto_rawDescGZIP() []byte {
	file_openshield_v1_risk_proto_rawDescOnce.Do(func() {
		file_openshield_v1_risk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openshield_v1_risk_proto_rawDesc), len(file_openshield_v1_risk_proto_rawDesc)))
	})
	return file_openshield_v1_risk_proto_rawDescData
}

var file_openshield_v1_risk_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_openshield_v1_risk_proto_goTypes = []any{
	(*RiskUpdate)(nil),            // 0: openshield.v1.RiskUpdate
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_openshield_v1_risk_proto_depIdxs = []int32{
	1, // 0: openshield.v1.RiskUpdate.computed_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_openshield_v1_risk_proto_init() }
func file_openshield_v1_risk_proto_init() {
	if File_openshield_v1_risk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openshield_v1_risk_proto_rawDesc), len(file_openshield_v1_risk_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openshield_v1_risk_proto_goTypes,
		DependencyIndexes: file_openshield_v1_risk_proto_depIdxs,
		MessageInfos:      file_openshield_v1_risk_proto_msgTypes,
	}.Build()
	File_openshield_v1_risk_proto = out.File
	file_openshield_v1_risk_proto_goTypes = nil
	file_openshield_v1_risk_proto_depIdxs = nil
}
