// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: openshield/v1/rules.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RuleValidator names a built-in validator a custom rule may pair with its pattern. A
// custom rule ships a PATTERN and a NAMED validator, never executable code — so an
// operator-authored rule cannot introduce a code-execution path (the pattern runs on Go's
// RE2 engine, which is linear-time and immune to catastrophic backtracking / ReDoS).
type RuleValidator int32

const (
	RuleValidator_RULE_VALIDATOR_NONE RuleValidator = 0 // the pattern is the validator
	RuleValidator_RULE_VALIDATOR_LUHN RuleValidator = 1 // digits pass the Luhn checksum
)

// Enum value maps for RuleValidator.
var (
	RuleValidator_name = map[int32]string{
		0: "RULE_VALIDATOR_NONE",
		1: "RULE_VALIDATOR_LUHN",
	}
	RuleValidator_value = map[string]int32{
		"RULE_VALIDATOR_NONE": 0,
		"RULE_VALIDATOR_LUHN": 1,
	}
)

func (x RuleValidator) Enum() *RuleValidator {
	p := new(RuleValidator)
	*p = x
	return p
}

func (x RuleValidator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuleValidator) Descriptor() protoreflect.EnumDescriptor {
	return file_openshield_v1_rules_proto_enumTypes[0].Descriptor()
}

func (RuleValidator) Type() protoreflect.EnumType {
	return &file_openshield_v1_rules_proto_enumTypes[0]
}

func (x RuleValidator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuleValidator.Descriptor instead.
func (RuleValidator) EnumDescriptor() ([]byte, []int) {
	return file_openshield_v1_rules_proto_rawDescGZIP(), []int{0}
}

// DetectorRule is one operator-authored declarative detector (Phase D3): a regex pattern,
// the confidence to report, and an optional named validator. rule_id identifies the rule
// for bundle management; it is NOT surfaced to the pipeline (custom hits report the
// generic DETECTOR_TYPE_CUSTOM, preserving the no-leak closed enum).
type DetectorRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        uint32                 `protobuf:"varint,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Pattern       string                 `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Validator     RuleValidator          `protobuf:"varint,4,opt,name=validator,proto3,enum=openshield.v1.RuleValidator" json:"validator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectorRule) Reset() {
	*x = DetectorRule{}
	mi := &file_openshield_v1_rules_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectorRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectorRule) ProtoMessage() {}

func (x *DetectorRule) ProtoReflect() protoreflect.Message {
	mi := &file_openshield_v1_rules_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectorRule.ProtoReflect.Descriptor instead.
func (*DetectorRule) Descriptor() ([]byte, []int) {
	return file_openshield_v1_rules_proto_rawDescGZIP(), []int{0}
}

func (x *DetectorRule) GetRuleId() uint32 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

func (x *DetectorRule) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *DetectorRule) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *DetectorRule) GetValidator() RuleValidator {
	if x != nil {
		return x.Validator
	}
	return RuleValidator_RULE_VALIDATOR_NONE
}

// RuleBundle is a set of custom rules an operator authors and approves together.
type RuleBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*DetectorRule        `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	IssuedAt      int64                  `protobuf:"varint,2,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleBundle) Reset() {
	*x = RuleBundle{}
	mi := &file_openshield_v1_rules_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleBundle) ProtoMessage() {}

func (x *RuleBundle) ProtoReflect() protoreflect.Message {
	mi := &file_openshield_v1_rules_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleBundle.ProtoReflect.Descriptor instead.
func (*RuleBundle) Descriptor() ([]byte, []int) {
	return file_openshield_v1_rules_proto_rawDescGZIP(), []int{1}
}

func (x *RuleBundle) GetRules() []*DetectorRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *RuleBundle) GetIssuedAt() int64 {
	if x != nil {
		return x.IssuedAt
	}
	return 0
}

// SignedRuleBundle carries a marshaled RuleBundle and an Ed25519 signature over those
// exact bytes. The node loads the rules ONLY if the signature verifies against a trusted
// operator public key — a compromised control plane can distribute this message but cannot
// forge the signature, so it cannot inject detection rules (the T2 model preserving D14).
type SignedRuleBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bundle        []byte                 `protobuf:"bytes,1,opt,name=bundle,proto3" json:"bundle,omitempty"`       // the marshaled RuleBundle
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"` // Ed25519 signature over `bundle`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedRuleBundle) Reset() {
	*x = SignedRuleBundle{}
	mi := &file_openshield_v1_rules_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedRuleBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedRuleBundle) ProtoMessage() {}

func (x *SignedRuleBundle) ProtoReflect() protoreflect.Message {
	mi := &file_openshield_v1_rules_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedRuleBundle.ProtoReflect.Descriptor instead.
func (*SignedRuleBundle) Descriptor() ([]byte, []int) {
	return file_openshield_v1_rules_proto_rawDescGZIP(), []int{2}
}

func (x *SignedRuleBundle) GetBundle() []byte {
	if x != nil {
		return x.Bundle
	}
	return nil
}

func (x *SignedRuleBundle) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// SignedIndex wraps a serialized, k-anonymized DLP detection index (EDM single-value,
// multi-cell record, or IDM document-fingerprint — each already hash-only) with an
// Ed25519 signature the node verifies against a trusted operator public key before loading
// it into the sandbox (ADR-9). `kind` binds the index type into the signature, so a signed
// index of one kind cannot be presented as another. As with SignedRuleBundle, a compromised
// control plane may DISTRIBUTE this message but cannot FORGE the signature — so it cannot
// inject or poison the detection data the DLP detector matches against (T2/D14).
type SignedIndex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`           // "edm" | "record" | "idm"
	Index         []byte                 `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`         // the serialized index (the existing Marshal() bytes)
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"` // Ed25519 signature over a domain-separated (kind, index)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedIndex) Reset() {
	*x = SignedIndex{}
	mi := &file_openshield_v1_rules_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedIndex) ProtoMessage() {}

func (x *SignedIndex) ProtoReflect() protoreflect.Message {
	mi := &file_openshield_v1_rules_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedIndex.ProtoReflect.Descriptor instead.
func (*SignedIndex) Descriptor() ([]byte, []int) {
	return file_openshield_v1_rules_proto_rawDescGZIP(), []int{3}
}

func (x *SignedIndex) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SignedIndex) GetIndex() []byte {
	if x != nil {
		return x.Index
	}
	return nil
}

func (x *SignedIndex) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_openshield_v1_rules_proto protoreflect.FileDescriptor

const file_openshield_v1_rules_proto_rawDesc = "" +
	"\n" +
	"\x19openshield/v1/rules.proto\x12\ropenshield.v1\"\x9d\x01\n" +
	"\fDetectorRule\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\rR\x06ruleId\x12\x18\n" +
	"\apattern\x18\x02 \x01(\tR\apattern\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12:\n" +
	"\tvalidator\x18\x04 \x01(\x0e2\x1c.openshield.v1.RuleValidatorR\tvalidator\"\\\n" +
	"\n" +
	"RuleBundle\x121\n" +
	"\x05rules\x18\x01 \x03(\v2\x1b.openshield.v1.DetectorRuleR\x05rules\x12\x1b\n" +
	"\tissued_at\x18\x02 \x01(\x03R\bissuedAt\"H\n" +
	"\x10SignedRuleBundle\x12\x16\n" +
	"\x06bundle\x18\x01 \x01(\fR\x06bundle\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"U\n" +
	"\vSignedIndex\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x14\n" +
	"\x05index\x18\x02 \x01(\fR\x05index\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature*A\n" +
	"\rRuleValidator\x12\x17\n" +
	"\x13RULE_VALIDATOR_NONE\x10\x00\x12\x17\n" +
	"\x13RULE_VALIDATOR_LUHN\x10\x01B@Z>github.com/lucianoengel/openshield/internal/core/corev1;corev1b\x06proto3"

var (
	file_openshield_v1_rules_proto_rawDescOnce sync.Once
	file_openshield_v1_rules_proto_rawDescData []byte
)

func file_openshield_v1_rules_proto_rawDescGZIP() []byte {
	file_openshield_v1_rules_proto_rawDescOnce.Do(func() {
		file_openshield_v1_rules_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openshield_v1_rules_proto_rawDesc), len(file_openshield_v1_rules_proto_rawDesc)))
	})
	return file_openshield_v1_rules_proto_rawDescData
}

var file_openshield_v1_rules_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_openshield_v1_rules_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_openshield_v1_rules_proto_goTypes = []any{
	(RuleValidator)(0),       // 0: openshield.v1.RuleValidator
	(*DetectorRule)(nil),     // 1: openshield.v1.DetectorRule
	(*RuleBundle)(nil),       // 2: openshield.v1.RuleBundle
	(*SignedRuleBundle)(nil), // 3: openshield.v1.SignedRuleBundle
	(*SignedIndex)(nil),      // 4: openshield.v1.SignedIndex
}
var file_openshield_v1_rules_proto_depIdxs = []int32{
	0, // 0: openshield.v1.DetectorRule.validator:type_name -> openshield.v1.RuleValidator
	1, // 1: openshield.v1.RuleBundle.rules:type_name -> openshield.v1.DetectorRule
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_openshield_v1_rules_proto_init() }
func file_openshield_v1_rules_proto_init() {
	if File_openshield_v1_rules_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openshield_v1_rules_proto_rawDesc), len(file_openshield_v1_rules_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openshield_v1_rules_proto_goTypes,
		DependencyIndexes: file_openshield_v1_rules_proto_depIdxs,
		EnumInfos:         file_openshield_v1_rules_proto_enumTypes,
		MessageInfos:      file_openshield_v1_rules_proto_msgTypes,
	}.Build()
	File_openshield_v1_rules_proto = out.File
	file_openshield_v1_rules_proto_goTypes = nil
	file_openshield_v1_rules_proto_depIdxs = nil
}
