// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: openshield/v1/signed.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SignedTelemetry wraps a telemetry payload with the agent's identity signature
// (T-017). The control plane verifies the signature against the ENROLLED key and
// the sequence for suppression/replay before persisting, so the fleet view is
// attributable — not self-asserted (D41/D44).
//
// signature is over the canonical envelope (agent_id, sequence, payload), the
// same bytes the agent signs and the control plane checks. One monotonic
// sequence per agent across all kinds, so a dropped message leaves a hole.
type SignedTelemetry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`       // event | classification | decision
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"` // marshalled Event / ClassificationSummary / Decision
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedTelemetry) Reset() {
	*x = SignedTelemetry{}
	mi := &file_openshield_v1_signed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedTelemetry) ProtoMessage() {}

func (x *SignedTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_openshield_v1_signed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedTelemetry.ProtoReflect.Descriptor instead.
func (*SignedTelemetry) Descriptor() ([]byte, []int) {
	return file_openshield_v1_signed_proto_rawDescGZIP(), []int{0}
}

func (x *SignedTelemetry) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SignedTelemetry) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *SignedTelemetry) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SignedTelemetry) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SignedTelemetry) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// SignedUpdate wraps a control-plane→gateway data update (risk, posture) with an Ed25519
// signature over the payload bytes (SEC-1). The gateway verifies the signature against a
// trusted publisher key BEFORE interpreting the payload, so anyone who can merely PUBLISH
// to the NATS subject (past broker mTLS) cannot forge risk/posture for any subject — only
// the holder of the signing key can. Risk is signed by the control plane; posture by the
// reporting agent (different key authorities, same envelope).
type SignedUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`     // the marshalled RiskUpdate / PostureUpdate
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"` // Ed25519 signature over `payload`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedUpdate) Reset() {
	*x = SignedUpdate{}
	mi := &file_openshield_v1_signed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedUpdate) ProtoMessage() {}

func (x *SignedUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_openshield_v1_signed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedUpdate.ProtoReflect.Descriptor instead.
func (*SignedUpdate) Descriptor() ([]byte, []int) {
	return file_openshield_v1_signed_proto_rawDescGZIP(), []int{1}
}

func (x *SignedUpdate) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SignedUpdate) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_openshield_v1_signed_proto protoreflect.FileDescriptor

const file_openshield_v1_signed_proto_rawDesc = "" +
	"\n" +
	"\x1aopenshield/v1/signed.proto\x12\ropenshield.v1\"\x94\x01\n" +
	"\x0fSignedTelemetry\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\"F\n" +
	"\fSignedUpdate\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignatureB@Z>github.com/lucianoengel/openshield/internal/core/corev1;corev1b\x06proto3"

var (
	file_openshield_v1_signed_proto_rawDescOnce sync.Once
	file_openshield_v1_signed_proto_rawDescData []byte
)

func file_openshield_v1_signed_proto_rawDescGZIP() []byte {
	file_openshield_v1_signed_proto_rawDescOnce.Do(func() {
		file_openshield_v1_signed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openshield_v1_signed_proto_rawDesc), len(file_openshield_v1_signed_proto_rawDesc)))
	})
	return file_openshield_v1_signed_proto_rawDescData
}

var file_openshield_v1_signed_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_openshield_v1_signed_proto_goTypes = []any{
	(*SignedTelemetry)(nil), // 0: openshield.v1.SignedTelemetry
	(*SignedUpdate)(nil),    // 1: openshield.v1.SignedUpdate
}
var file_openshield_v1_signed_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_openshield_v1_signed_proto_init() }
func file_openshield_v1_signed_proto_init() {
	if File_openshield_v1_signed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openshield_v1_signed_proto_rawDesc), len(file_openshield_v1_signed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openshield_v1_signed_proto_goTypes,
		DependencyIndexes: file_openshield_v1_signed_proto_depIdxs,
		MessageInfos:      file_openshield_v1_signed_proto_msgTypes,
	}.Build()
	File_openshield_v1_signed_proto = out.File
	file_openshield_v1_signed_proto_goTypes = nil
	file_openshield_v1_signed_proto_depIdxs = nil
}
