// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: openshield/v1/threat.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ThreatCategory is the closed set of network threat-intel signal kinds (NIPS-2).
// It is DISTINCT from the DLP DetectorType: a DLP detector flags sensitive CONTENT
// (and its enum is closed to avoid leaking what was detected), whereas a threat
// match flags a known-bad DESTINATION or request — public threat-intel, already in
// the flow's metadata. Conflating them would be a category error.
type ThreatCategory int32

const (
	ThreatCategory_THREAT_CATEGORY_UNSPECIFIED ThreatCategory = 0
	// The flow's host is, or is a subdomain of, a known-bad domain.
	ThreatCategory_THREAT_CATEGORY_IOC_DOMAIN ThreatCategory = 1
	// The flow's destination IP is a known-bad address or in a known-bad CIDR.
	ThreatCategory_THREAT_CATEGORY_IOC_IP ThreatCategory = 2
	// The request path matches a network URI signature.
	ThreatCategory_THREAT_CATEGORY_URI_SIGNATURE ThreatCategory = 3
	// The flow BODY matched an operator content signature (NIPS-2 body-content
	// engine), matched in the sandboxed worker. The indicator id is the rule id;
	// the matched bytes never cross the classification boundary.
	ThreatCategory_THREAT_CATEGORY_CONTENT_SIGNATURE ThreatCategory = 4
	// The flow's TLS CLIENT fingerprint (JA3) matched a known-bad one — the only
	// category here that describes the client rather than the destination, and so the
	// only one that still says something when the domain is new, rotated or encrypted
	// away. Weaker than the others by nature: a JA3 identifies a TLS library at a
	// version, shared by every program built on it, so a match is evidence and not
	// proof. Its confidence is reported below 1.0 to say so.
	ThreatCategory_THREAT_CATEGORY_JA3 ThreatCategory = 5
)

// Enum value maps for ThreatCategory.
var (
	ThreatCategory_name = map[int32]string{
		0: "THREAT_CATEGORY_UNSPECIFIED",
		1: "THREAT_CATEGORY_IOC_DOMAIN",
		2: "THREAT_CATEGORY_IOC_IP",
		3: "THREAT_CATEGORY_URI_SIGNATURE",
		4: "THREAT_CATEGORY_CONTENT_SIGNATURE",
		5: "THREAT_CATEGORY_JA3",
	}
	ThreatCategory_value = map[string]int32{
		"THREAT_CATEGORY_UNSPECIFIED":       0,
		"THREAT_CATEGORY_IOC_DOMAIN":        1,
		"THREAT_CATEGORY_IOC_IP":            2,
		"THREAT_CATEGORY_URI_SIGNATURE":     3,
		"THREAT_CATEGORY_CONTENT_SIGNATURE": 4,
		"THREAT_CATEGORY_JA3":               5,
	}
)

func (x ThreatCategory) Enum() *ThreatCategory {
	p := new(ThreatCategory)
	*p = x
	return p
}

func (x ThreatCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ThreatCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_openshield_v1_threat_proto_enumTypes[0].Descriptor()
}

func (ThreatCategory) Type() protoreflect.EnumType {
	return &file_openshield_v1_threat_proto_enumTypes[0]
}

func (x ThreatCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ThreatCategory.Descriptor instead.
func (ThreatCategory) EnumDescriptor() ([]byte, []int) {
	return file_openshield_v1_threat_proto_rawDescGZIP(), []int{0}
}

// IntentVerb is the CLOSED vocabulary of coordinated response (ADR-12 Tier-2, SOAR-7).
//
// Closed for the same reason Action is (D14): the threat is a compromised control plane expressing an
// arbitrary action that an endpoint then performs. Three verbs, each meaning something a LOCAL policy
// interprets — the server publishes DATA, the endpoint decides. Adding a member here is a one-at-a-time
// owner decision and must also edit the enum-completeness test.
type IntentVerb int32

const (
	IntentVerb_INTENT_VERB_UNSPECIFIED IntentVerb = 0
	// Watch this subject harder: a policy may lower thresholds, sample more, or require step-up auth.
	IntentVerb_INTENT_VERB_ELEVATE_SCRUTINY IntentVerb = 1
	// Contain this subject: a policy may block its flows and refuse its new executions. HIGH-IMPACT —
	// publication requires a four-eyes approval and a bounded blast radius.
	IntentVerb_INTENT_VERB_CONTAIN IntentVerb = 2
	// Stop trusting this subject's credentials: a policy may refuse its tokens and require re-attestation.
	// HIGH-IMPACT.
	IntentVerb_INTENT_VERB_REVOKE_TRUST IntentVerb = 3
)

// Enum value maps for IntentVerb.
var (
	IntentVerb_name = map[int32]string{
		0: "INTENT_VERB_UNSPECIFIED",
		1: "INTENT_VERB_ELEVATE_SCRUTINY",
		2: "INTENT_VERB_CONTAIN",
		3: "INTENT_VERB_REVOKE_TRUST",
	}
	IntentVerb_value = map[string]int32{
		"INTENT_VERB_UNSPECIFIED":      0,
		"INTENT_VERB_ELEVATE_SCRUTINY": 1,
		"INTENT_VERB_CONTAIN":          2,
		"INTENT_VERB_REVOKE_TRUST":     3,
	}
)

func (x IntentVerb) Enum() *IntentVerb {
	p := new(IntentVerb)
	*p = x
	return p
}

func (x IntentVerb) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IntentVerb) Descriptor() protoreflect.EnumDescriptor {
	return file_openshield_v1_threat_proto_enumTypes[1].Descriptor()
}

func (IntentVerb) Type() protoreflect.EnumType {
	return &file_openshield_v1_threat_proto_enumTypes[1]
}

func (x IntentVerb) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IntentVerb.Descriptor instead.
func (IntentVerb) EnumDescriptor() ([]byte, []int) {
	return file_openshield_v1_threat_proto_rawDescGZIP(), []int{1}
}

// FleetVerb is the CLOSED vocabulary of fleet-wide operational control (PLAT-9).
//
// DELIBERATELY NOT a fourth IntentVerb. Every member of that vocabulary CAUSES enforcement — contain,
// revoke trust, elevate scrutiny — and "stop enforcing" is its opposite. Folding them together would mean
// one signed-message type whose members both start and stop the product's action, and any consumer
// mis-handling the discriminator fails in the most dangerous possible direction.
//
// It is also the most attractive forgery target in the system: ONE accepted message turns the product off
// across a fleet. That is why it carries a monotonic SEQUENCE (a captured message cannot be replayed) and
// MANDATORY time bounds (a captured message cannot last), on top of the signature.
type FleetVerb int32

const (
	FleetVerb_FLEET_VERB_UNSPECIFIED FleetVerb = 0
	// Stop ENFORCING fleet-wide. Detection, decisions and the audit trail continue — this is not "stop
	// seeing". Publication requires a four-eyes approval.
	FleetVerb_FLEET_VERB_ENFORCEMENT_DISABLE FleetVerb = 1
	// Resume enforcing. Signed too: a forged restore would undo a disable an operator engaged during an
	// incident.
	FleetVerb_FLEET_VERB_ENFORCEMENT_RESTORE FleetVerb = 2
)

// Enum value maps for FleetVerb.
var (
	FleetVerb_name = map[int32]string{
		0: "FLEET_VERB_UNSPECIFIED",
		1: "FLEET_VERB_ENFORCEMENT_DISABLE",
		2: "FLEET_VERB_ENFORCEMENT_RESTORE",
	}
	FleetVerb_value = map[string]int32{
		"FLEET_VERB_UNSPECIFIED":         0,
		"FLEET_VERB_ENFORCEMENT_DISABLE": 1,
		"FLEET_VERB_ENFORCEMENT_RESTORE": 2,
	}
)

func (x FleetVerb) Enum() *FleetVerb {
	p := new(FleetVerb)
	*p = x
	return p
}

func (x FleetVerb) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FleetVerb) Descriptor() protoreflect.EnumDescriptor {
	return file_openshield_v1_threat_proto_enumTypes[2].Descriptor()
}

func (FleetVerb) Type() protoreflect.EnumType {
	return &file_openshield_v1_threat_proto_enumTypes[2]
}

func (x FleetVerb) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FleetVerb.Descriptor instead.
func (FleetVerb) EnumDescriptor() ([]byte, []int) {
	return file_openshield_v1_threat_proto_rawDescGZIP(), []int{2}
}

// ThreatMatch is one threat-intel hit on a flow. It carries the category and a
// confidence (1.0 for a definitive IOC match) and an OPAQUE indicator id (a feed or
// rule identifier an analyst can trace) — never the matched content, so the
// classification-crossing stays free of raw matched strings.
type ThreatMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      ThreatCategory         `protobuf:"varint,1,opt,name=category,proto3,enum=openshield.v1.ThreatCategory" json:"category,omitempty"`
	Confidence    float64                `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	IndicatorId   string                 `protobuf:"bytes,3,opt,name=indicator_id,json=indicatorId,proto3" json:"indicator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreatMatch) Reset() {
	*x = ThreatMatch{}
	mi := &file_openshield_v1_threat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreatMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatMatch) ProtoMessage() {}

func (x *ThreatMatch) ProtoReflect() protoreflect.Message {
	mi := &file_openshield_v1_threat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatMatch.ProtoReflect.Descriptor instead.
func (*ThreatMatch) Descriptor() ([]byte, []int) {
	return file_openshield_v1_threat_proto_rawDescGZIP(), []int{0}
}

func (x *ThreatMatch) GetCategory() ThreatCategory {
	if x != nil {
		return x.Category
	}
	return ThreatCategory_THREAT_CATEGORY_UNSPECIFIED
}

func (x *ThreatMatch) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ThreatMatch) GetIndicatorId() string {
	if x != nil {
		return x.IndicatorId
	}
	return ""
}

// ThreatClassification holds the threat matches for a flow — the network analogue
// of the DLP LocalClassification, on its own axis.
type ThreatClassification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Matches       []*ThreatMatch         `protobuf:"bytes,2,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreatClassification) Reset() {
	*x = ThreatClassification{}
	mi := &file_openshield_v1_threat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreatClassification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatClassification) ProtoMessage() {}

func (x *ThreatClassification) ProtoReflect() protoreflect.Message {
	mi := &file_openshield_v1_threat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatClassification.ProtoReflect.Descriptor instead.
func (*ThreatClassification) Descriptor() ([]byte, []int) {
	return file_openshield_v1_threat_proto_rawDescGZIP(), []int{1}
}

func (x *ThreatClassification) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ThreatClassification) GetMatches() []*ThreatMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

// ResponseIntent is the control plane's coordinated-response signal (SOAR-7/ADR-12 Tier-2).
//
// It is DATA, not an instruction. A consumer verifies the signature, reads it as typed policy CONTEXT, and
// its own policy decides what the verb means for it — an endpoint whose policy ignores intents is
// unaffected, which is a property of the design rather than a gap in it.
//
// It carries no content (D10/D29): a pseudonymous subject (D23), a closed verb, and time bounds.
type ResponseIntent struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	IntentId string                 `protobuf:"bytes,1,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"` // stable id; the four-eyes approval is bound to it
	Verb     IntentVerb             `protobuf:"varint,2,opt,name=verb,proto3,enum=openshield.v1.IntentVerb" json:"verb,omitempty"`
	Subject  string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`  // pseudonymous subject or entity key (D23)
	Version  uint32                 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"` // consumers reject a version they do not understand
	IssuedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	// expires_at is MANDATORY in practice: a contain with no expiry is a permanent quarantine nobody
	// remembers issuing. A consumer treats an expired intent as absent, so a stale containment cannot
	// outlive the control plane that issued it.
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Reason        string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"` // operator-facing justification; never content
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseIntent) Reset() {
	*x = ResponseIntent{}
	mi := &file_openshield_v1_threat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseIntent) ProtoMessage() {}

func (x *ResponseIntent) ProtoReflect() protoreflect.Message {
	mi := &file_openshield_v1_threat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseIntent.ProtoReflect.Descriptor instead.
func (*ResponseIntent) Descriptor() ([]byte, []int) {
	return file_openshield_v1_threat_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseIntent) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

func (x *ResponseIntent) GetVerb() IntentVerb {
	if x != nil {
		return x.Verb
	}
	return IntentVerb_INTENT_VERB_UNSPECIFIED
}

func (x *ResponseIntent) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *ResponseIntent) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ResponseIntent) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *ResponseIntent) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ResponseIntent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// FleetControl is a signed fleet-wide operational instruction (PLAT-9).
//
// It carries no subject: it applies to every consumer, which is precisely what makes it dangerous and
// what the sequence and expiry bound.
type FleetControl struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ControlId string                 `protobuf:"bytes,1,opt,name=control_id,json=controlId,proto3" json:"control_id,omitempty"`
	Verb      FleetVerb              `protobuf:"varint,2,opt,name=verb,proto3,enum=openshield.v1.FleetVerb" json:"verb,omitempty"`
	Version   uint32                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"` // consumers reject a version they do not understand
	// sequence is MONOTONIC per control plane. A consumer refuses anything at or below the highest it has
	// applied, so a captured DISABLE cannot be replayed after an operator restored enforcement.
	Sequence uint64                 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	IssuedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	// expires_at is MANDATORY: a disable with no expiry is a product that is off and nobody remembers
	// turning off. A consumer treats an expired control as absent.
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Reason        string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"` // operator-facing justification; never content
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FleetControl) Reset() {
	*x = FleetControl{}
	mi := &file_openshield_v1_threat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetControl) ProtoMessage() {}

func (x *FleetControl) ProtoReflect() protoreflect.Message {
	mi := &file_openshield_v1_threat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetControl.ProtoReflect.Descriptor instead.
func (*FleetControl) Descriptor() ([]byte, []int) {
	return file_openshield_v1_threat_proto_rawDescGZIP(), []int{3}
}

func (x *FleetControl) GetControlId() string {
	if x != nil {
		return x.ControlId
	}
	return ""
}

func (x *FleetControl) GetVerb() FleetVerb {
	if x != nil {
		return x.Verb
	}
	return FleetVerb_FLEET_VERB_UNSPECIFIED
}

func (x *FleetControl) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *FleetControl) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *FleetControl) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *FleetControl) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *FleetControl) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_openshield_v1_threat_proto protoreflect.FileDescriptor

const file_openshield_v1_threat_proto_rawDesc = "" +
	"\n" +
	"\x1aopenshield/v1/threat.proto\x12\ropenshield.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8b\x01\n" +
	"\vThreatMatch\x129\n" +
	"\bcategory\x18\x01 \x01(\x0e2\x1d.openshield.v1.ThreatCategoryR\bcategory\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01R\n" +
	"confidence\x12!\n" +
	"\findicator_id\x18\x03 \x01(\tR\vindicatorId\"g\n" +
	"\x14ThreatClassification\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x124\n" +
	"\amatches\x18\x02 \x03(\v2\x1a.openshield.v1.ThreatMatchR\amatches\"\x9c\x02\n" +
	"\x0eResponseIntent\x12\x1b\n" +
	"\tintent_id\x18\x01 \x01(\tR\bintentId\x12-\n" +
	"\x04verb\x18\x02 \x01(\x0e2\x19.openshield.v1.IntentVerbR\x04verb\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x18\n" +
	"\aversion\x18\x04 \x01(\rR\aversion\x127\n" +
	"\tissued_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\"\x9d\x02\n" +
	"\fFleetControl\x12\x1d\n" +
	"\n" +
	"control_id\x18\x01 \x01(\tR\tcontrolId\x12,\n" +
	"\x04verb\x18\x02 \x01(\x0e2\x18.openshield.v1.FleetVerbR\x04verb\x12\x18\n" +
	"\aversion\x18\x03 \x01(\rR\aversion\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x04R\bsequence\x127\n" +
	"\tissued_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason*\xd0\x01\n" +
	"\x0eThreatCategory\x12\x1f\n" +
	"\x1bTHREAT_CATEGORY_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aTHREAT_CATEGORY_IOC_DOMAIN\x10\x01\x12\x1a\n" +
	"\x16THREAT_CATEGORY_IOC_IP\x10\x02\x12!\n" +
	"\x1dTHREAT_CATEGORY_URI_SIGNATURE\x10\x03\x12%\n" +
	"!THREAT_CATEGORY_CONTENT_SIGNATURE\x10\x04\x12\x17\n" +
	"\x13THREAT_CATEGORY_JA3\x10\x05*\x82\x01\n" +
	"\n" +
	"IntentVerb\x12\x1b\n" +
	"\x17INTENT_VERB_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cINTENT_VERB_ELEVATE_SCRUTINY\x10\x01\x12\x17\n" +
	"\x13INTENT_VERB_CONTAIN\x10\x02\x12\x1c\n" +
	"\x18INTENT_VERB_REVOKE_TRUST\x10\x03*o\n" +
	"\tFleetVerb\x12\x1a\n" +
	"\x16FLEET_VERB_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eFLEET_VERB_ENFORCEMENT_DISABLE\x10\x01\x12\"\n" +
	"\x1eFLEET_VERB_ENFORCEMENT_RESTORE\x10\x02B@Z>github.com/lucianoengel/openshield/internal/core/corev1;corev1b\x06proto3"

var (
	file_openshield_v1_threat_proto_rawDescOnce sync.Once
	file_openshield_v1_threat_proto_rawDescData []byte
)

func file_openshield_v1_threat_proto_rawDescGZIP() []byte {
	file_openshield_v1_threat_proto_rawDescOnce.Do(func() {
		file_openshield_v1_threat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openshield_v1_threat_proto_rawDesc), len(file_openshield_v1_threat_proto_rawDesc)))
	})
	return file_openshield_v1_threat_proto_rawDescData
}

var file_openshield_v1_threat_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_openshield_v1_threat_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_openshield_v1_threat_proto_goTypes = []any{
	(ThreatCategory)(0),           // 0: openshield.v1.ThreatCategory
	(IntentVerb)(0),               // 1: openshield.v1.IntentVerb
	(FleetVerb)(0),                // 2: openshield.v1.FleetVerb
	(*ThreatMatch)(nil),           // 3: openshield.v1.ThreatMatch
	(*ThreatClassification)(nil),  // 4: openshield.v1.ThreatClassification
	(*ResponseIntent)(nil),        // 5: openshield.v1.ResponseIntent
	(*FleetControl)(nil),          // 6: openshield.v1.FleetControl
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_openshield_v1_threat_proto_depIdxs = []int32{
	0, // 0: openshield.v1.ThreatMatch.category:type_name -> openshield.v1.ThreatCategory
	3, // 1: openshield.v1.ThreatClassification.matches:type_name -> openshield.v1.ThreatMatch
	1, // 2: openshield.v1.ResponseIntent.verb:type_name -> openshield.v1.IntentVerb
	7, // 3: openshield.v1.ResponseIntent.issued_at:type_name -> google.protobuf.Timestamp
	7, // 4: openshield.v1.ResponseIntent.expires_at:type_name -> google.protobuf.Timestamp
	2, // 5: openshield.v1.FleetControl.verb:type_name -> openshield.v1.FleetVerb
	7, // 6: openshield.v1.FleetControl.issued_at:type_name -> google.protobuf.Timestamp
	7, // 7: openshield.v1.FleetControl.expires_at:type_name -> google.protobuf.Timestamp
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_openshield_v1_threat_proto_init() }
func file_openshield_v1_threat_proto_init() {
	if File_openshield_v1_threat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openshield_v1_threat_proto_rawDesc), len(file_openshield_v1_threat_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openshield_v1_threat_proto_goTypes,
		DependencyIndexes: file_openshield_v1_threat_proto_depIdxs,
		EnumInfos:         file_openshield_v1_threat_proto_enumTypes,
		MessageInfos:      file_openshield_v1_threat_proto_msgTypes,
	}.Build()
	File_openshield_v1_threat_proto = out.File
	file_openshield_v1_threat_proto_goTypes = nil
	file_openshield_v1_threat_proto_depIdxs = nil
}
