// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: openshield/v1/threat.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ThreatCategory is the closed set of network threat-intel signal kinds (NIPS-2).
// It is DISTINCT from the DLP DetectorType: a DLP detector flags sensitive CONTENT
// (and its enum is closed to avoid leaking what was detected), whereas a threat
// match flags a known-bad DESTINATION or request — public threat-intel, already in
// the flow's metadata. Conflating them would be a category error.
type ThreatCategory int32

const (
	ThreatCategory_THREAT_CATEGORY_UNSPECIFIED ThreatCategory = 0
	// The flow's host is, or is a subdomain of, a known-bad domain.
	ThreatCategory_THREAT_CATEGORY_IOC_DOMAIN ThreatCategory = 1
	// The flow's destination IP is a known-bad address or in a known-bad CIDR.
	ThreatCategory_THREAT_CATEGORY_IOC_IP ThreatCategory = 2
	// The request path matches a network URI signature.
	ThreatCategory_THREAT_CATEGORY_URI_SIGNATURE ThreatCategory = 3
	// The flow BODY matched an operator content signature (NIPS-2 body-content
	// engine), matched in the sandboxed worker. The indicator id is the rule id;
	// the matched bytes never cross the classification boundary.
	ThreatCategory_THREAT_CATEGORY_CONTENT_SIGNATURE ThreatCategory = 4
)

// Enum value maps for ThreatCategory.
var (
	ThreatCategory_name = map[int32]string{
		0: "THREAT_CATEGORY_UNSPECIFIED",
		1: "THREAT_CATEGORY_IOC_DOMAIN",
		2: "THREAT_CATEGORY_IOC_IP",
		3: "THREAT_CATEGORY_URI_SIGNATURE",
		4: "THREAT_CATEGORY_CONTENT_SIGNATURE",
	}
	ThreatCategory_value = map[string]int32{
		"THREAT_CATEGORY_UNSPECIFIED":       0,
		"THREAT_CATEGORY_IOC_DOMAIN":        1,
		"THREAT_CATEGORY_IOC_IP":            2,
		"THREAT_CATEGORY_URI_SIGNATURE":     3,
		"THREAT_CATEGORY_CONTENT_SIGNATURE": 4,
	}
)

func (x ThreatCategory) Enum() *ThreatCategory {
	p := new(ThreatCategory)
	*p = x
	return p
}

func (x ThreatCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ThreatCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_openshield_v1_threat_proto_enumTypes[0].Descriptor()
}

func (ThreatCategory) Type() protoreflect.EnumType {
	return &file_openshield_v1_threat_proto_enumTypes[0]
}

func (x ThreatCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ThreatCategory.Descriptor instead.
func (ThreatCategory) EnumDescriptor() ([]byte, []int) {
	return file_openshield_v1_threat_proto_rawDescGZIP(), []int{0}
}

// ThreatMatch is one threat-intel hit on a flow. It carries the category and a
// confidence (1.0 for a definitive IOC match) and an OPAQUE indicator id (a feed or
// rule identifier an analyst can trace) — never the matched content, so the
// classification-crossing stays free of raw matched strings.
type ThreatMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      ThreatCategory         `protobuf:"varint,1,opt,name=category,proto3,enum=openshield.v1.ThreatCategory" json:"category,omitempty"`
	Confidence    float64                `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	IndicatorId   string                 `protobuf:"bytes,3,opt,name=indicator_id,json=indicatorId,proto3" json:"indicator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreatMatch) Reset() {
	*x = ThreatMatch{}
	mi := &file_openshield_v1_threat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreatMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatMatch) ProtoMessage() {}

func (x *ThreatMatch) ProtoReflect() protoreflect.Message {
	mi := &file_openshield_v1_threat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatMatch.ProtoReflect.Descriptor instead.
func (*ThreatMatch) Descriptor() ([]byte, []int) {
	return file_openshield_v1_threat_proto_rawDescGZIP(), []int{0}
}

func (x *ThreatMatch) GetCategory() ThreatCategory {
	if x != nil {
		return x.Category
	}
	return ThreatCategory_THREAT_CATEGORY_UNSPECIFIED
}

func (x *ThreatMatch) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ThreatMatch) GetIndicatorId() string {
	if x != nil {
		return x.IndicatorId
	}
	return ""
}

// ThreatClassification holds the threat matches for a flow — the network analogue
// of the DLP LocalClassification, on its own axis.
type ThreatClassification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Matches       []*ThreatMatch         `protobuf:"bytes,2,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreatClassification) Reset() {
	*x = ThreatClassification{}
	mi := &file_openshield_v1_threat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreatClassification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatClassification) ProtoMessage() {}

func (x *ThreatClassification) ProtoReflect() protoreflect.Message {
	mi := &file_openshield_v1_threat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatClassification.ProtoReflect.Descriptor instead.
func (*ThreatClassification) Descriptor() ([]byte, []int) {
	return file_openshield_v1_threat_proto_rawDescGZIP(), []int{1}
}

func (x *ThreatClassification) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ThreatClassification) GetMatches() []*ThreatMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

var File_openshield_v1_threat_proto protoreflect.FileDescriptor

const file_openshield_v1_threat_proto_rawDesc = "" +
	"\n" +
	"\x1aopenshield/v1/threat.proto\x12\ropenshield.v1\"\x8b\x01\n" +
	"\vThreatMatch\x129\n" +
	"\bcategory\x18\x01 \x01(\x0e2\x1d.openshield.v1.ThreatCategoryR\bcategory\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01R\n" +
	"confidence\x12!\n" +
	"\findicator_id\x18\x03 \x01(\tR\vindicatorId\"g\n" +
	"\x14ThreatClassification\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x124\n" +
	"\amatches\x18\x02 \x03(\v2\x1a.openshield.v1.ThreatMatchR\amatches*\xb7\x01\n" +
	"\x0eThreatCategory\x12\x1f\n" +
	"\x1bTHREAT_CATEGORY_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aTHREAT_CATEGORY_IOC_DOMAIN\x10\x01\x12\x1a\n" +
	"\x16THREAT_CATEGORY_IOC_IP\x10\x02\x12!\n" +
	"\x1dTHREAT_CATEGORY_URI_SIGNATURE\x10\x03\x12%\n" +
	"!THREAT_CATEGORY_CONTENT_SIGNATURE\x10\x04B@Z>github.com/lucianoengel/openshield/internal/core/corev1;corev1b\x06proto3"

var (
	file_openshield_v1_threat_proto_rawDescOnce sync.Once
	file_openshield_v1_threat_proto_rawDescData []byte
)

func file_openshield_v1_threat_proto_rawDescGZIP() []byte {
	file_openshield_v1_threat_proto_rawDescOnce.Do(func() {
		file_openshield_v1_threat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openshield_v1_threat_proto_rawDesc), len(file_openshield_v1_threat_proto_rawDesc)))
	})
	return file_openshield_v1_threat_proto_rawDescData
}

var file_openshield_v1_threat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_openshield_v1_threat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_openshield_v1_threat_proto_goTypes = []any{
	(ThreatCategory)(0),          // 0: openshield.v1.ThreatCategory
	(*ThreatMatch)(nil),          // 1: openshield.v1.ThreatMatch
	(*ThreatClassification)(nil), // 2: openshield.v1.ThreatClassification
}
var file_openshield_v1_threat_proto_depIdxs = []int32{
	0, // 0: openshield.v1.ThreatMatch.category:type_name -> openshield.v1.ThreatCategory
	1, // 1: openshield.v1.ThreatClassification.matches:type_name -> openshield.v1.ThreatMatch
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_openshield_v1_threat_proto_init() }
func file_openshield_v1_threat_proto_init() {
	if File_openshield_v1_threat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openshield_v1_threat_proto_rawDesc), len(file_openshield_v1_threat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openshield_v1_threat_proto_goTypes,
		DependencyIndexes: file_openshield_v1_threat_proto_depIdxs,
		EnumInfos:         file_openshield_v1_threat_proto_enumTypes,
		MessageInfos:      file_openshield_v1_threat_proto_msgTypes,
	}.Build()
	File_openshield_v1_threat_proto = out.File
	file_openshield_v1_threat_proto_goTypes = nil
	file_openshield_v1_threat_proto_depIdxs = nil
}
