package config

// GatewayFields declares every configuration field cmd/openshield-gateway reads (PLAT-5 follow-up).
//
// ALL BOOTSTRAP, and that is a statement about what the gateway IS rather than a limitation. It is a
// network appliance: listen addresses, firewall marks, certificate and key paths, the worker binary,
// feed locations. Those are node-local by nature - two gateways in different network positions do not
// share them - so storing them centrally would be modelling them wrong, not modelling them better.
//
// It also means the gateway does NOT need database credentials to read its configuration. That matters:
// it sits in the network path and is the most exposed component here, so handing it a DSN so it could
// read dynamic settings would be a step in the wrong direction. If a genuinely fleet-wide gateway
// setting appears later it should arrive over the SIGNED channel the gateway already verifies risk and
// intents on - decided then, against a real case, rather than guessed at now.
//
// The immediate win is the one D262 brought the server: a malformed value FAILS THE BOOT with a precise
// error instead of silently falling back to a default, which is how a typo in an interval quietly turns
// a feature off.
var GatewayFields = []Field{
	{Key: "OPENSHIELD_LISTEN", Scope: ScopeBootstrap, Kind: KindString, Default: "127.0.0.1:8080",
		Description: "Address the forward proxy listens on."},
	{Key: "OPENSHIELD_DSN", Scope: ScopeBootstrap, Kind: KindString, Default: "postgres://openshield:dev@127.0.0.1:55432/openshield?sslmode=disable",
		Description: "Postgres connection string for the gateway's ledger and aggregate."},
	{Key: "OPENSHIELD_NATS_URL", Scope: ScopeBootstrap, Kind: KindString, Default: "",
		Description: "NATS URL for signed risk/posture channels and telemetry. Empty leaves those channels inert."},
	{Key: "OPENSHIELD_WORKER_BIN", Scope: ScopeBootstrap, Kind: KindPath, Default: "/usr/local/bin/openshield-worker",
		Description: "Sandboxed parser worker binary. Content is classified there, never in this process (D29)."},
	{Key: "OPENSHIELD_WORKER_POOL", Scope: ScopeBootstrap, Kind: KindInt, Default: "4",
		Description: "How many parser workers to run."},
	{Key: "OPENSHIELD_SIGNER_FILE", Scope: ScopeBootstrap, Kind: KindString, Default: "/var/lib/openshield/gateway-signer.state",
		Description: "Forward-secure ledger signer state (D12). Its directory must survive restarts or the chain cannot continue."},
	{Key: "OPENSHIELD_SEQ_FILE", Scope: ScopeBootstrap, Kind: KindString, Default: "",
		Description: "Persisted telemetry sequence. Without it a restart replays sequence numbers and the control plane sees a gap."},
	{Key: "OPENSHIELD_AGENT_ID", Scope: ScopeBootstrap, Kind: KindString, Default: "gateway",
		Description: "Identity this gateway enrolls and signs telemetry under."},
	{Key: "OPENSHIELD_ENROLL_URL", Scope: ScopeBootstrap, Kind: KindString, Default: "",
		Description: "Control-plane enrollment endpoint. Set together with OPENSHIELD_NATS_URL to enable signed telemetry."},
	{Key: "OPENSHIELD_ENROLL_TOKEN", Scope: ScopeBootstrap, Kind: KindSecret, Default: "",
		Description: "Single-use enrollment token (D44)."},
	{Key: "OPENSHIELD_CONTROL_PLANE_KEY", Scope: ScopeBootstrap, Kind: KindPath, Default: "",
		Description: "File holding the ed25519 PUBLIC key that signed fleet-wide controls are verified against (PLAT-9). Unset means this host accepts no fleet control and can only be stopped locally."},
	{Key: "OPENSHIELD_BREAK_GLASS", Scope: ScopeBootstrap, Kind: KindString, Default: "/etc/openshield/EMERGENCY_DISABLE",
		Description: "Local break-glass file. While it EXISTS, this host stops ENFORCING but keeps detecting and auditing \u2014 the answer to \"how do I stop this\" when the control plane is unreachable."},
	{Key: "OPENSHIELD_BREAK_GLASS_POLL", Scope: ScopeBootstrap, Kind: KindDuration, Default: "10s",
		Description: "How often the break-glass file is checked. Short: this is the emergency path, and a slow one is not one."},
	{Key: "OPENSHIELD_ENFORCE", Scope: ScopeBootstrap, Kind: KindString, Default: "",
		Description: "Set to any value to ENFORCE. Unset is observe-only (D1) - the default is deliberately the one that cannot break traffic."},
	{Key: "OPENSHIELD_REDIRECT_URL", Scope: ScopeBootstrap, Kind: KindString, Default: "https://openshield.invalid/coaching",
		Description: "Page a blocked user is sent to."},
	{Key: "OPENSHIELD_RETENTION_INTERVAL", Scope: ScopeBootstrap, Kind: KindDuration, Default: "24h",
		Description: "How often the gateway purges its aggregate under the retention window (D81/D20)."},
	{Key: "OPENSHIELD_POLICY_PACK", Scope: ScopeBootstrap, Kind: KindString, Default: "",
		Description: "Compliance policy pack(s) to load (DLP-5b)."},
	{Key: "OPENSHIELD_POLICY_CUSTOM", Scope: ScopeBootstrap, Kind: KindPath, Default: "",
		Description: "Optional custom policy file layered over the packs."},
	{Key: "OPENSHIELD_INSPECT_RESPONSES", Scope: ScopeBootstrap, Kind: KindString, Default: "",
		Description: "Set to inspect RESPONSE bodies as well as requests."},
	{Key: "OPENSHIELD_INTERCEPT_CA_CERT", Scope: ScopeBootstrap, Kind: KindPath, Default: "",
		Description: "Interception CA certificate (D75). TLS bodies are inspected only when this and its key are both set."},
	{Key: "OPENSHIELD_INTERCEPT_CA_KEY", Scope: ScopeBootstrap, Kind: KindSecret, Default: "",
		Description: "Interception CA private key. Holding it means the gateway can mint certificates for any host it intercepts."},
	{Key: "OPENSHIELD_NO_INTERCEPT", Scope: ScopeBootstrap, Kind: KindString, Default: "",
		Description: "Comma-separated hosts to tunnel WITHOUT interception - pinned or sensitive destinations."},
	{Key: "OPENSHIELD_RISK_PUBKEY", Scope: ScopeBootstrap, Kind: KindPath, Default: "",
		Description: "Control-plane public key risk updates are verified against (SEC-1). Unset leaves risk continuous-verification INERT; unsigned risk is never applied."},
	{Key: "OPENSHIELD_POSTURE_ROSTER", Scope: ScopeBootstrap, Kind: KindPath, Default: "",
		Description: "Enrolled posture publishers, one '<identity> <base64-pubkey>' per line. Unset leaves the posture channel inert."},
	{Key: "OPENSHIELD_ATTEST", Scope: ScopeBootstrap, Kind: KindString, Default: "",
		Description: "Set to require device attestation."},
	{Key: "OPENSHIELD_ATTEST_TTL", Scope: ScopeBootstrap, Kind: KindDuration, Default: "",
		Description: "How long an attestation stays valid."},
	{Key: "OPENSHIELD_ATTEST_ENROLLMENTS", Scope: ScopeBootstrap, Kind: KindPath, Default: "",
		Description: "Enrolled attestation identities. Unset means the verifier is empty and every device is unattested (fails closed)."},
	{Key: "OPENSHIELD_ENROLL_PREAUTH_TOKENS", Scope: ScopeBootstrap, Kind: KindSecret, Default: "",
		Description: "Comma-separated pre-authorization tokens (R34-2). Unset means any device with a co-resident TPM can self-enroll."},
	{Key: "OPENSHIELD_EK_ROOTS", Scope: ScopeBootstrap, Kind: KindPath, Default: "",
		Description: "PEM bundle of TPM EK roots (R34-2). Unset means a fabricated EK, including swtpm, passes enrollment."},
	{Key: "OPENSHIELD_ACCESS_MODE", Scope: ScopeBootstrap, Kind: KindString, Default: "",
		Description: "Set to run as the ZTNA access proxy instead of the forward proxy."},
	{Key: "OPENSHIELD_ACCESS_LISTEN", Scope: ScopeBootstrap, Kind: KindString, Default: "127.0.0.1:8443",
		Description: "Address the access proxy listens on."},
	{Key: "OPENSHIELD_ACCESS_CLIENT_CA", Scope: ScopeBootstrap, Kind: KindPath, Default: "",
		Description: "CA the access proxy verifies client certificates against."},
	{Key: "OPENSHIELD_ACCESS_SERVER_CERT", Scope: ScopeBootstrap, Kind: KindPath, Default: "",
		Description: "Access proxy server certificate."},
	{Key: "OPENSHIELD_ACCESS_SERVER_KEY", Scope: ScopeBootstrap, Kind: KindSecret, Default: "",
		Description: "Access proxy server private key."},
	{Key: "OPENSHIELD_ACCESS_POLICY", Scope: ScopeBootstrap, Kind: KindPath, Default: "",
		Description: "Access policy evaluated per request."},
	{Key: "OPENSHIELD_ACCESS_CATALOG", Scope: ScopeBootstrap, Kind: KindString, Default: "",
		Description: "Services this access gateway fronts. An access gateway must front at least one."},
	{Key: "OPENSHIELD_OIDC_ISSUER", Scope: ScopeBootstrap, Kind: KindString, Default: "",
		Description: "OIDC issuer (ZT-2). Set to resolve SSO identity."},
	{Key: "OPENSHIELD_OIDC_AUDIENCE", Scope: ScopeBootstrap, Kind: KindString, Default: "",
		Description: "Audience an OIDC token must carry."},
	{Key: "OPENSHIELD_OIDC_ROLE_CLAIM", Scope: ScopeBootstrap, Kind: KindString, Default: "groups",
		Description: "Token claim read as the caller's roles."},
	{Key: "OPENSHIELD_OIDC_JWKS_URL", Scope: ScopeBootstrap, Kind: KindString, Default: "",
		Description: "JWKS endpoint for issuer keys."},
	{Key: "OPENSHIELD_OIDC_JWKS_INTERVAL", Scope: ScopeBootstrap, Kind: KindDuration, Default: "5m",
		Description: "How often JWKS keys are refreshed."},
	{Key: "OPENSHIELD_OIDC_KEYS_DIR", Scope: ScopeBootstrap, Kind: KindPath, Default: "",
		Description: "Directory of static OIDC keys, as an alternative to JWKS."},
	{Key: "OPENSHIELD_OIDC_LEEWAY", Scope: ScopeBootstrap, Kind: KindDuration, Default: "60s",
		Description: "Clock-skew allowance when validating token times."},
	{Key: "OPENSHIELD_OIDC_DPOP", Scope: ScopeBootstrap, Kind: KindString, Default: "",
		Description: "Set to require DPoP proof-of-possession."},
	{Key: "OPENSHIELD_OIDC_DPOP_CACHE", Scope: ScopeBootstrap, Kind: KindInt, Default: "8192",
		Description: "Replay-cache size for DPoP proofs."},
	{Key: "OPENSHIELD_IOC_FEED", Scope: ScopeBootstrap, Kind: KindPath, Default: "",
		Description: "Local IOC feed (NIPS-2). Unset, with no URL either, leaves the threat-intel engine inert."},
	{Key: "OPENSHIELD_IOC_FEED_KEY", Scope: ScopeBootstrap, Kind: KindPath, Default: "",
		Description: "File holding the ed25519 PUBLIC key the local IOC feed is verified against, with its detached signature at <feed>.sig. Unset loads the feed UNVERIFIED — anything that can write that file then decides what this gateway blocks."},
	{Key: "OPENSHIELD_IOC_FEED_RELOAD", Scope: ScopeBootstrap, Kind: KindDuration, Default: "0s",
		Description: "How often the local IOC feed is re-read. 0 disables reloading."},
	{Key: "OPENSHIELD_IOC_FEED_URL", Scope: ScopeBootstrap, Kind: KindString, Default: "",
		Description: "Remote IOC feed, fetched with a bounded conditional GET."},
	{Key: "OPENSHIELD_IOC_FEED_URL_RELOAD", Scope: ScopeBootstrap, Kind: KindDuration, Default: "0s",
		Description: "How often the remote IOC feed is re-fetched. 0 disables reloading."},
	{Key: "OPENSHIELD_CASB_CATALOG", Scope: ScopeBootstrap, Kind: KindPath, Default: "",
		Description: "Cloud-service catalog (DLP-2). Unset leaves cloud-upload awareness inert."},
	{Key: "OPENSHIELD_CASB_CATALOG_RELOAD", Scope: ScopeBootstrap, Kind: KindDuration, Default: "0s",
		Description: "How often the CASB catalog is re-read. 0 disables reloading."},
	{Key: "OPENSHIELD_TPROXY_LISTEN", Scope: ScopeBootstrap, Kind: KindString, Default: "",
		Description: "Address for the NIPS-1 transparent inline data plane. Empty disables it."},
	{Key: "OPENSHIELD_TPROXY_INSTALL_RULES", Scope: ScopeBootstrap, Kind: KindString, Default: "",
		Description: "Set to 1 to install the TPROXY firewall rules (needs CAP_NET_ADMIN)."},
	{Key: "OPENSHIELD_TPROXY_DPORTS", Scope: ScopeBootstrap, Kind: KindString, Default: "80,443",
		Description: "Destination ports redirected into the transparent data plane."},
	{Key: "OPENSHIELD_TPROXY_MARK", Scope: ScopeBootstrap, Kind: KindString, Default: "1",
		Description: "Firewall mark for TPROXY traffic."},
	{Key: "OPENSHIELD_TPROXY_TABLE", Scope: ScopeBootstrap, Kind: KindString, Default: "100",
		Description: "Routing table used by the TPROXY rules."},
	{Key: "OPENSHIELD_TPROXY_RETRY", Scope: ScopeBootstrap, Kind: KindDuration, Default: "5s",
		Description: "Retry interval when installing TPROXY rules."},
	{Key: "OPENSHIELD_DNS_SINK_LISTEN", Scope: ScopeBootstrap, Kind: KindString, Default: "",
		Description: "Address for the NIPS-8 preventive DNS resolver. Set with an upstream to enable it."},
	{Key: "OPENSHIELD_DNS_UPSTREAM", Scope: ScopeBootstrap, Kind: KindString, Default: "",
		Description: "Upstream resolver that normal queries are forwarded to."},
	{Key: "OPENSHIELD_DNS_REDIRECT", Scope: ScopeBootstrap, Kind: KindString, Default: "",
		Description: "Transparent :53 redirect scope: local (this host's own DNS) or off."},
	{Key: "OPENSHIELD_DNS_REDIRECT_MARK", Scope: ScopeBootstrap, Kind: KindString, Default: "0x1d5",
		Description: "Firewall mark exempting the resolver's OWN upstream queries from the redirect - without it the resolver redirects to itself."},
}
