package config

// ServerFields declares EVERY configuration field cmd/openshield-server reads (PLAT-5).
//
// One declaration per field, used for BOTH reading and describing — there is deliberately no second
// list. That is what makes a future UI form structurally unable to offer a setting the binary ignores,
// and it is the reason this file is verbose: each entry is the field"s whole contract, checked by the
// compiler rather than expressed in a struct tag the compiler cannot read.
//
// A test asserts every OPENSHIELD_* variable read by the server binary appears here, so a field cannot
// drift back out of the schema.
var ServerFields = []Field{
	// BOOTSTRAP-ONLY: this names the file source itself, so it can only come from the environment. It is
	// still declared, because a field the schema cannot see is a field a UI cannot show — and "where do
	// my settings come from" is the first thing an operator asks.
	{Key: "OPENSHIELD_CONFIG_FILE", Kind: KindPath, Default: "",
		Description: "Optional KEY=VALUE file consulted after the environment. Read from the environment only."},
	{Key: "OPENSHIELD_DSN", Kind: KindString, Default: "postgres://openshield:dev@127.0.0.1:55432/openshield?sslmode=disable",
		Description: "Postgres connection string for the fleet aggregate and control-plane state."},
	{Key: "OPENSHIELD_NATS_URL", Kind: KindString, Default: "nats://127.0.0.1:4222",
		Description: "NATS URL the control plane consumes telemetry from."},
	{Key: "OPENSHIELD_HTTP_ADDR", Kind: KindString, Default: "",
		Description: "Address for the enrollment/operator HTTP surface. Empty disables it."},
	{Key: "OPENSHIELD_METRICS_ADDR", Kind: KindString, Default: "",
		Description: "Address for the Prometheus endpoint (PLAT-4). Belongs on an internal/firewalled interface."},
	{Key: "OPENSHIELD_METRICS_TOKEN", Kind: KindSecret, Default: "",
		Description: "Bearer token required to scrape /metrics. Unset means the endpoint is unauthenticated."},
	{Key: "OPENSHIELD_APP_ROLE", Kind: KindString, Default: "",
		Description: "Least-privilege Postgres role the server switches to after migrating."},
	{Key: "OPENSHIELD_APP_PASSWORD", Kind: KindSecret, Default: "",
		Description: "Password for the least-privilege role."},
	{Key: "OPENSHIELD_RISK_SIGNING_KEY", Kind: KindPath, Default: "",
		Description: "File holding the raw ed25519 PRIVATE key that signs risk and intent publications (SEC-1). Unset means risk publishing stays inert rather than forgeable."},
	{Key: "OPENSHIELD_INTENT_KEY", Kind: KindPath, Default: "",
		Description: "File holding the raw ed25519 PUBLIC key an intent must verify against before the IdP responder acts (SOAR-8). Unset means the responder does not start."},
	{Key: "OPENSHIELD_CORRELATE_INTERVAL", Kind: KindDuration, Default: "0s",
		Description: "How often scheduled correlation runs (SOAR-2). Zero disables it — incidents are then raised only when an operator asks."},
	{Key: "OPENSHIELD_CORRELATE_WINDOW", Kind: KindDuration, Default: "1h",
		Description: "Look-back window for both correlation rules."},
	{Key: "OPENSHIELD_CORRELATE_MIN_ALERTS", Kind: KindInt, Default: "3",
		Description: "Alerts within the window needed to raise a burst incident."},
	{Key: "OPENSHIELD_CORRELATE_MIN_DOMAINS", Kind: KindInt, Default: "2",
		Description: "Distinct domains needed to raise a cross-domain incident (XDR-4)."},
	{Key: "OPENSHIELD_PLAYBOOKS", Kind: KindPath, Default: "",
		Description: "Playbook configuration file (SOAR-4). Unset means orchestration is off."},
	{Key: "OPENSHIELD_PLAYBOOK_INTERVAL", Kind: KindDuration, Default: "1m",
		Description: "How often the playbook engine looks for work."},
	{Key: "OPENSHIELD_TI_FEED", Kind: KindPath, Default: "",
		Description: "Threat-intel feed file re-ingested on a timer (SOAR-5). Its detached signature is read from <path>.sig."},
	{Key: "OPENSHIELD_TI_FEED_KEY", Kind: KindPath, Default: "",
		Description: "File holding the ed25519 PUBLIC key threat-intel feeds are verified against. Unset ingests feeds UNVERIFIED."},
	{Key: "OPENSHIELD_TI_FEED_NAME", Kind: KindString, Default: "operator",
		Description: "Feed name recorded as the provenance of its indicators."},
	{Key: "OPENSHIELD_TI_FEED_FORMAT", Kind: KindString, Default: "native",
		Description: "Threat-intel feed format: native or csv. Never inferred from content."},
	{Key: "OPENSHIELD_TI_FEED_INTERVAL", Kind: KindDuration, Default: "1h",
		Description: "How often the threat-intel feed is re-ingested."},
	{Key: "OPENSHIELD_IDP_ENDPOINT", Kind: KindString, Default: "",
		Description: "Identity-provider endpoint the IdP responder calls (SOAR-8). Its actions are IRREVERSIBLE: intent expiry restores nothing."},
	{Key: "OPENSHIELD_IDP_NAME", Kind: KindString, Default: "idp",
		Description: "Connector name recorded against every action it performs."},
	{Key: "OPENSHIELD_IDP_TOKEN", Kind: KindSecret, Default: "",
		Description: "Bearer credential for the identity-provider endpoint."},
	{Key: "OPENSHIELD_IDP_TIMEOUT", Kind: KindDuration, Default: "10s",
		Description: "Per-call timeout for the IdP responder."},
	{Key: "OPENSHIELD_ITSM_ENDPOINT", Kind: KindString, Default: "",
		Description: "Ticketing endpoint for incident/ticket sync (SOAR-8)."},
	{Key: "OPENSHIELD_ITSM_NAME", Kind: KindString, Default: "tickets",
		Description: "Ticketing connector name."},
	{Key: "OPENSHIELD_ITSM_TOKEN", Kind: KindSecret, Default: "",
		Description: "Bearer credential for the ticketing endpoint."},
	{Key: "OPENSHIELD_ITSM_TIMEOUT", Kind: KindDuration, Default: "10s",
		Description: "Per-call timeout for ticketing."},
	{Key: "OPENSHIELD_ITSM_INTERVAL", Kind: KindDuration, Default: "5m",
		Description: "How often tickets are synced. Sync-back lags by up to one interval (polling, not a webhook)."},
	{Key: "OPENSHIELD_ITSM_MIN_SEVERITY", Kind: KindString, Default: "high",
		Description: "Minimum incident severity that opens a ticket."},
	{Key: "OPENSHIELD_ITSM_CLOSED_STATUSES", Kind: KindString, Default: "closed,resolved,done",
		Description: "Remote statuses that mean the ticket is closed. Any OTHER status is ignored, never assumed closed."},
	{Key: "OPENSHIELD_ALERT_WEBHOOK", Kind: KindString, Default: "",
		Description: "Alert sinks, comma-separated. An entry may be name=url so a routing rule can select it (SOAR-9)."},
	{Key: "OPENSHIELD_ALERT_WEBHOOK_SECRET", Kind: KindSecret, Default: "",
		Description: "HMAC key signing each alert body so a receiver can verify its origin."},
	{Key: "OPENSHIELD_ALERT_RETRIES", Kind: KindInt, Default: "3",
		Description: "Delivery attempts per sink before giving up (a 4xx is not retried)."},
	{Key: "OPENSHIELD_ALERT_ROUTES", Kind: KindPath, Default: "",
		Description: "Notification routing table (SOAR-9). Unset means fan out to every sink."},
	{Key: "OPENSHIELD_OVERDUE_THRESHOLD", Kind: KindDuration, Default: "15m",
		Description: "Silence after which an agent is reported overdue (D50/D51)."},
	{Key: "OPENSHIELD_OVERDUE_INTERVAL", Kind: KindDuration, Default: "5m",
		Description: "How often the overdue check runs."},
	{Key: "OPENSHIELD_RETENTION_INTERVAL", Kind: KindDuration, Default: "24h",
		Description: "How often the fleet-aggregate retention purge runs."},
	{Key: "OPENSHIELD_FLEET_RETENTION", Kind: KindDuration, Default: "2160h",
		Description: "How long fleet-aggregate telemetry is kept before purge (D81/D20)."},
	{Key: "OPENSHIELD_NOTIFY_DEDUPE_RETENTION", Kind: KindDuration, Default: "24h",
		Description: "How long durable notify-dedupe ids are kept (SIEM-12)."},
	{Key: "OPENSHIELD_PEER_UEBA_THRESHOLD", Kind: KindString, Default: "",
		Description: "Peer-UEBA risk threshold above which an alert is recorded (D54)."},
	{Key: "OPENSHIELD_PEER_UEBA_COOLDOWN", Kind: KindDuration, Default: "",
		Description: "Minimum gap between peer-UEBA alerts for one subject."},
	{Key: "OPENSHIELD_UEBA_PERSIST_INTERVAL", Kind: KindDuration, Default: "",
		Description: "How often UEBA baselines are persisted."},
	{Key: "OPENSHIELD_CEF_SYSLOG_LISTEN", Kind: KindString, Default: "",
		Description: "Address to receive CEF-over-syslog on (SIEM-4). Empty disables ingest."},
	{Key: "OPENSHIELD_CLOUDTRAIL_DIR", Kind: KindString, Default: "",
		Description: "Directory polled for CloudTrail records (SIEM-4)."},
	{Key: "OPENSHIELD_WEF_DIR", Kind: KindString, Default: "",
		Description: "Directory polled for Windows Event Forwarding records (SIEM-4)."},
}
