package config

// ServerFields declares EVERY configuration field cmd/openshield-server reads (PLAT-5).
//
// One declaration per field, used for BOTH reading and describing — there is deliberately no second
// list. That is what makes a future UI form structurally unable to offer a setting the binary ignores,
// and it is the reason this file is verbose: each entry is the field"s whole contract, checked by the
// compiler rather than expressed in a struct tag the compiler cannot read.
//
// A test asserts every OPENSHIELD_* variable read by the server binary appears here, so a field cannot
// drift back out of the schema.
var ServerFields = []Field{
	// BOOTSTRAP is deliberately SMALL: connection, listening, identity, and where credentials live —
	// what a process needs to start and reach this database. Everything else is DYNAMIC and stored, so a
	// change applies to the whole deployment without touching a host. A test bounds the bootstrap set,
	// because the way this split dies is by accretion.
	// BOOTSTRAP-ONLY: this names the file source itself, so it can only come from the environment. It is
	// still declared, because a field the schema cannot see is a field a UI cannot show — and "where do
	// my settings come from" is the first thing an operator asks.
	{Key: "OPENSHIELD_CONFIG_FILE", Scope: ScopeBootstrap, Kind: KindPath, Default: "",
		Description: "Optional KEY=VALUE file consulted after the environment. Read from the environment only."},
	{Key: "OPENSHIELD_CONFIG_POLL", Scope: ScopeBootstrap, Kind: KindDuration, Default: "15s",
		Description: "How often this process checks for a new configuration revision. Bootstrap, because a process that could not reach the store would never learn to."},
	{Key: "OPENSHIELD_BREAKGLASS", Scope: ScopeBootstrap, Kind: KindString, Default: "",
		Description: "Comma-separated dynamic keys this host deliberately overrides from the environment. The override applies AND is reported."},
	{Key: "OPENSHIELD_DSN", Scope: ScopeBootstrap, Kind: KindString, Default: "postgres://openshield:dev@127.0.0.1:55432/openshield?sslmode=disable",
		Description: "Postgres connection string for the fleet aggregate and control-plane state."},
	{Key: "OPENSHIELD_NATS_URL", Scope: ScopeBootstrap, Kind: KindString, Default: "nats://127.0.0.1:4222",
		Description: "NATS URL the control plane consumes telemetry from."},
	{Key: "OPENSHIELD_HTTP_ADDR", Scope: ScopeBootstrap, Kind: KindString, Default: "",
		Description: "Address for the enrollment/operator HTTP surface. Empty disables it."},
	{Key: "OPENSHIELD_METRICS_ADDR", Scope: ScopeBootstrap, Kind: KindString, Default: "",
		Description: "Address for the Prometheus endpoint (PLAT-4). Belongs on an internal/firewalled interface."},
	{Key: "OPENSHIELD_METRICS_TOKEN", Scope: ScopeBootstrap, Kind: KindSecret, Default: "",
		Description: "Bearer token required to scrape /metrics. Unset means the endpoint is unauthenticated."},
	{Key: "OPENSHIELD_APP_ROLE", Scope: ScopeBootstrap, Kind: KindString, Default: "",
		Description: "Least-privilege Postgres role the server switches to after migrating."},
	{Key: "OPENSHIELD_APP_PASSWORD", Scope: ScopeBootstrap, Kind: KindSecret, Default: "",
		Description: "Password for the least-privilege role."},
	{Key: "OPENSHIELD_RISK_SIGNING_KEY", Scope: ScopeBootstrap, Kind: KindPath, Default: "",
		Description: "File holding the raw ed25519 PRIVATE key that signs risk and intent publications (SEC-1). Unset means risk publishing stays inert rather than forgeable."},
	{Key: "OPENSHIELD_INTENT_KEY", Scope: ScopeBootstrap, Kind: KindPath, Default: "",
		Description: "File holding the raw ed25519 PUBLIC key an intent must verify against before the IdP responder acts (SOAR-8). Unset means the responder does not start."},
	{Key: "OPENSHIELD_BEACON_INTERVAL", Scope: ScopeDynamic, Kind: KindDuration, Default: "0s",
		Description: "How often the beaconing sweep runs (NIPS-6). Zero disables it. Much longer than the correlation interval: a check-in rhythm needs a wide window, and re-scanning it every correlation tick would be redundant work."},
	{Key: "OPENSHIELD_BEACON_WINDOW", Scope: ScopeDynamic, Kind: KindDuration, Default: "24h",
		Description: "Look-back window for beaconing. A rhythm is not visible in an hour; too narrow a window is how a real beacon goes unseen."},
	{Key: "OPENSHIELD_BEACON_MIN_CONTACTS", Scope: ScopeDynamic, Kind: KindInt, Default: "8",
		Description: "Contacts required before regularity is measured. Below about eight, 'regular' is not a measurement — three contacts give two intervals, and two intervals are always regular."},
	{Key: "OPENSHIELD_BEACON_MIN_REGULARITY", Scope: ScopeDynamic, Kind: KindString, Default: "0.85",
		Description: "Regularity score (0-1) at or above which a destination is reported. Lowering it trades false positives for low-and-slow coverage; that dial is the operator's."},
	{Key: "OPENSHIELD_BEACON_ALLOWLIST", Scope: ScopeDynamic, Kind: KindString, Default: "",
		Description: "Comma-separated destinations never reported as beacons. Legitimate software beacons constantly, and a detector whose output is mostly known-good gets muted."},
	{Key: "OPENSHIELD_CORRELATE_INTERVAL", Scope: ScopeDynamic, Kind: KindDuration, Default: "0s",
		Description: "How often scheduled correlation runs (SOAR-2). Zero disables it — incidents are then raised only when an operator asks."},
	{Key: "OPENSHIELD_CORRELATE_WINDOW", Scope: ScopeDynamic, Kind: KindDuration, Default: "1h",
		Description: "Look-back window for both correlation rules."},
	{Key: "OPENSHIELD_CORRELATE_MIN_ALERTS", Scope: ScopeDynamic, Kind: KindInt, Default: "3",
		Description: "Alerts within the window needed to raise a burst incident."},
	{Key: "OPENSHIELD_CORRELATE_MIN_DOMAINS", Scope: ScopeDynamic, Kind: KindInt, Default: "2",
		Description: "Distinct domains needed to raise a cross-domain incident (XDR-4)."},
	{Key: "OPENSHIELD_PLAYBOOKS", Scope: ScopeDynamic, Kind: KindPath, Default: "",
		Description: "Playbook configuration file (SOAR-4). Unset means orchestration is off."},
	{Key: "OPENSHIELD_PLAYBOOK_INTERVAL", Scope: ScopeDynamic, Kind: KindDuration, Default: "1m",
		Description: "How often the playbook engine looks for work."},
	{Key: "OPENSHIELD_TI_FEED", Scope: ScopeDynamic, Kind: KindPath, Default: "",
		Description: "Threat-intel feed file re-ingested on a timer (SOAR-5). Its detached signature is read from <path>.sig."},
	{Key: "OPENSHIELD_TI_FEED_KEY", Scope: ScopeBootstrap, Kind: KindPath, Default: "",
		Description: "File holding the ed25519 PUBLIC key threat-intel feeds are verified against. Unset ingests feeds UNVERIFIED."},
	{Key: "OPENSHIELD_TI_FEED_NAME", Scope: ScopeDynamic, Kind: KindString, Default: "operator",
		Description: "Feed name recorded as the provenance of its indicators."},
	{Key: "OPENSHIELD_TI_FEED_FORMAT", Scope: ScopeDynamic, Kind: KindString, Default: "native",
		Description: "Threat-intel feed format: native or csv. Never inferred from content."},
	{Key: "OPENSHIELD_TI_FEED_INTERVAL", Scope: ScopeDynamic, Kind: KindDuration, Default: "1h",
		Description: "How often the threat-intel feed is re-ingested."},
	{Key: "OPENSHIELD_IDP_ENDPOINT", Scope: ScopeDynamic, Kind: KindString, Default: "",
		Description: "Identity-provider endpoint the IdP responder calls (SOAR-8). Its actions are IRREVERSIBLE: intent expiry restores nothing."},
	{Key: "OPENSHIELD_IDP_NAME", Scope: ScopeDynamic, Kind: KindString, Default: "idp",
		Description: "Connector name recorded against every action it performs."},
	{Key: "OPENSHIELD_IDP_TOKEN", Scope: ScopeBootstrap, Kind: KindSecret, Default: "",
		Description: "Bearer credential for the identity-provider endpoint."},
	{Key: "OPENSHIELD_IDP_TIMEOUT", Scope: ScopeDynamic, Kind: KindDuration, Default: "10s",
		Description: "Per-call timeout for the IdP responder."},
	{Key: "OPENSHIELD_ITSM_ENDPOINT", Scope: ScopeDynamic, Kind: KindString, Default: "",
		Description: "Ticketing endpoint for incident/ticket sync (SOAR-8)."},
	{Key: "OPENSHIELD_ITSM_NAME", Scope: ScopeDynamic, Kind: KindString, Default: "tickets",
		Description: "Ticketing connector name."},
	{Key: "OPENSHIELD_ITSM_TOKEN", Scope: ScopeBootstrap, Kind: KindSecret, Default: "",
		Description: "Bearer credential for the ticketing endpoint."},
	{Key: "OPENSHIELD_ITSM_TIMEOUT", Scope: ScopeDynamic, Kind: KindDuration, Default: "10s",
		Description: "Per-call timeout for ticketing."},
	{Key: "OPENSHIELD_ITSM_INTERVAL", Scope: ScopeDynamic, Kind: KindDuration, Default: "5m",
		Description: "How often tickets are synced. Sync-back lags by up to one interval (polling, not a webhook)."},
	{Key: "OPENSHIELD_ITSM_MIN_SEVERITY", Scope: ScopeDynamic, Kind: KindString, Default: "high",
		Description: "Minimum incident severity that opens a ticket."},
	{Key: "OPENSHIELD_ITSM_CLOSED_STATUSES", Scope: ScopeDynamic, Kind: KindString, Default: "closed,resolved,done",
		Description: "Remote statuses that mean the ticket is closed. Any OTHER status is ignored, never assumed closed."},
	{Key: "OPENSHIELD_ALERT_WEBHOOK", Scope: ScopeDynamic, Kind: KindString, Default: "",
		Description: "Alert sinks, comma-separated. An entry may be name=url so a routing rule can select it (SOAR-9)."},
	{Key: "OPENSHIELD_ALERT_WEBHOOK_SECRET", Scope: ScopeBootstrap, Kind: KindSecret, Default: "",
		Description: "HMAC key signing each alert body so a receiver can verify its origin."},
	{Key: "OPENSHIELD_ALERT_RETRIES", Scope: ScopeDynamic, Kind: KindInt, Default: "3",
		Description: "Delivery attempts per sink before giving up (a 4xx is not retried)."},
	{Key: "OPENSHIELD_ALERT_ROUTES", Scope: ScopeDynamic, Kind: KindPath, Default: "",
		Description: "Notification routing table (SOAR-9). Unset means fan out to every sink."},
	{Key: "OPENSHIELD_OVERDUE_THRESHOLD", Scope: ScopeDynamic, Kind: KindDuration, Default: "15m",
		Description: "Silence after which an agent is reported overdue (D50/D51)."},
	{Key: "OPENSHIELD_OVERDUE_INTERVAL", Scope: ScopeDynamic, Kind: KindDuration, Default: "5m",
		Description: "How often the overdue check runs."},
	{Key: "OPENSHIELD_RETENTION_INTERVAL", Scope: ScopeDynamic, Kind: KindDuration, Default: "24h",
		Description: "How often the fleet-aggregate retention purge runs."},
	{Key: "OPENSHIELD_FLEET_RETENTION", Scope: ScopeDynamic, Kind: KindDuration, Default: "2160h",
		Description: "How long fleet-aggregate telemetry is kept before purge (D81/D20)."},
	{Key: "OPENSHIELD_NOTIFY_DEDUPE_RETENTION", Scope: ScopeDynamic, Kind: KindDuration, Default: "24h",
		Description: "How long durable notify-dedupe ids are kept (SIEM-12)."},
	{Key: "OPENSHIELD_PEER_UEBA_THRESHOLD", Scope: ScopeDynamic, Kind: KindString, Default: "",
		Description: "Peer-UEBA risk threshold above which an alert is recorded (D54)."},
	{Key: "OPENSHIELD_PEER_UEBA_COOLDOWN", Scope: ScopeDynamic, Kind: KindDuration, Default: "1h",
		Description: "Minimum gap between peer-UEBA alerts for one subject."},
	{Key: "OPENSHIELD_UEBA_PERSIST_INTERVAL", Scope: ScopeDynamic, Kind: KindDuration, Default: "5m",
		Description: "How often UEBA baselines are persisted."},
	{Key: "OPENSHIELD_CEF_SYSLOG_LISTEN", Scope: ScopeDynamic, Kind: KindString, Default: "",
		Description: "Address to receive CEF-over-syslog on (SIEM-4). Empty disables ingest."},
	{Key: "OPENSHIELD_CLOUDTRAIL_DIR", Scope: ScopeDynamic, Kind: KindString, Default: "",
		Description: "Directory polled for CloudTrail records (SIEM-4)."},
	{Key: "OPENSHIELD_WEF_DIR", Scope: ScopeDynamic, Kind: KindString, Default: "",
		Description: "Directory polled for Windows Event Forwarding records (SIEM-4)."},
}
